// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Webflow.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Webflow.OpenApiClient.Collections.Item.Fields.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \collections\{collection-id}\fields\{fieldId}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithFieldItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Webflow.OpenApiClient.Collections.Item.Fields.Item.WithFieldItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithFieldItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/collections/{collection%2Did}/fields/{fieldId}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Webflow.OpenApiClient.Collections.Item.Fields.Item.WithFieldItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithFieldItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/collections/{collection%2Did}/fields/{fieldId}", rawUrl)
        {
        }
        /// <summary>
        /// Delete a custom field in a collection. This endpoint does not currently support bulk deletion.Required scope | `cms:write`
        /// </summary>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Webflow.OpenApiClient.Models.DeleteField400Response">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Webflow.OpenApiClient.Models.DeleteField401Response">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Webflow.OpenApiClient.Models.DeleteField404Response">When receiving a 404 status code</exception>
        /// <exception cref="global::Soenneker.Webflow.OpenApiClient.Models.DeleteField429Response">When receiving a 429 status code</exception>
        /// <exception cref="global::Soenneker.Webflow.OpenApiClient.Models.DeleteField500Response">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task DeleteAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task DeleteAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToDeleteRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Webflow.OpenApiClient.Models.DeleteField400Response.CreateFromDiscriminatorValue },
                { "401", global::Soenneker.Webflow.OpenApiClient.Models.DeleteField401Response.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.Webflow.OpenApiClient.Models.DeleteField404Response.CreateFromDiscriminatorValue },
                { "429", global::Soenneker.Webflow.OpenApiClient.Models.DeleteField429Response.CreateFromDiscriminatorValue },
                { "500", global::Soenneker.Webflow.OpenApiClient.Models.DeleteField500Response.CreateFromDiscriminatorValue },
            };
            await RequestAdapter.SendNoContentAsync(requestInfo, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Update a custom field in a collection.Required scope | `cms:write`
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Webflow.OpenApiClient.Models.UpdateField200Response"/></returns>
        /// <param name="body">Details about the field of a collection</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Webflow.OpenApiClient.Models.UpdateField400Response">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Webflow.OpenApiClient.Models.UpdateField401Response">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Webflow.OpenApiClient.Models.UpdateField404Response">When receiving a 404 status code</exception>
        /// <exception cref="global::Soenneker.Webflow.OpenApiClient.Models.UpdateField429Response">When receiving a 429 status code</exception>
        /// <exception cref="global::Soenneker.Webflow.OpenApiClient.Models.UpdateField500Response">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Webflow.OpenApiClient.Models.UpdateField200Response?> PatchAsync(global::Soenneker.Webflow.OpenApiClient.Models.UpdateFieldRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Webflow.OpenApiClient.Models.UpdateField200Response> PatchAsync(global::Soenneker.Webflow.OpenApiClient.Models.UpdateFieldRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPatchRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Webflow.OpenApiClient.Models.UpdateField400Response.CreateFromDiscriminatorValue },
                { "401", global::Soenneker.Webflow.OpenApiClient.Models.UpdateField401Response.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.Webflow.OpenApiClient.Models.UpdateField404Response.CreateFromDiscriminatorValue },
                { "429", global::Soenneker.Webflow.OpenApiClient.Models.UpdateField429Response.CreateFromDiscriminatorValue },
                { "500", global::Soenneker.Webflow.OpenApiClient.Models.UpdateField500Response.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Webflow.OpenApiClient.Models.UpdateField200Response>(requestInfo, global::Soenneker.Webflow.OpenApiClient.Models.UpdateField200Response.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Delete a custom field in a collection. This endpoint does not currently support bulk deletion.Required scope | `cms:write`
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.DELETE, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Update a custom field in a collection.Required scope | `cms:write`
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">Details about the field of a collection</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPatchRequestInformation(global::Soenneker.Webflow.OpenApiClient.Models.UpdateFieldRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPatchRequestInformation(global::Soenneker.Webflow.OpenApiClient.Models.UpdateFieldRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.PATCH, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Webflow.OpenApiClient.Collections.Item.Fields.Item.WithFieldItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Webflow.OpenApiClient.Collections.Item.Fields.Item.WithFieldItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Webflow.OpenApiClient.Collections.Item.Fields.Item.WithFieldItemRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#pragma warning restore CS0618
