// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Serialization.Form;
using Microsoft.Kiota.Serialization.Json;
using Microsoft.Kiota.Serialization.Multipart;
using Microsoft.Kiota.Serialization.Text;
using Soenneker.Webflow.OpenApiClient.Asset_folders;
using Soenneker.Webflow.OpenApiClient.Assets;
using Soenneker.Webflow.OpenApiClient.Collections;
using Soenneker.Webflow.OpenApiClient.Form_submissions;
using Soenneker.Webflow.OpenApiClient.Forms;
using Soenneker.Webflow.OpenApiClient.Pages;
using Soenneker.Webflow.OpenApiClient.Sites;
using Soenneker.Webflow.OpenApiClient.Token;
using Soenneker.Webflow.OpenApiClient.Webhooks;
using Soenneker.Webflow.OpenApiClient.Workspaces;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Webflow.OpenApiClient
{
    /// <summary>
    /// The main entry point of the SDK, exposes the configuration and the fluent API.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WebflowOpenApiClient : BaseRequestBuilder
    {
        /// <summary>The asset_folders property</summary>
        public global::Soenneker.Webflow.OpenApiClient.Asset_folders.Asset_foldersRequestBuilder Asset_folders
        {
            get => new global::Soenneker.Webflow.OpenApiClient.Asset_folders.Asset_foldersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The assets property</summary>
        public global::Soenneker.Webflow.OpenApiClient.Assets.AssetsRequestBuilder Assets
        {
            get => new global::Soenneker.Webflow.OpenApiClient.Assets.AssetsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The collections property</summary>
        public global::Soenneker.Webflow.OpenApiClient.Collections.CollectionsRequestBuilder Collections
        {
            get => new global::Soenneker.Webflow.OpenApiClient.Collections.CollectionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The form_submissions property</summary>
        public global::Soenneker.Webflow.OpenApiClient.Form_submissions.Form_submissionsRequestBuilder Form_submissions
        {
            get => new global::Soenneker.Webflow.OpenApiClient.Form_submissions.Form_submissionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The forms property</summary>
        public global::Soenneker.Webflow.OpenApiClient.Forms.FormsRequestBuilder Forms
        {
            get => new global::Soenneker.Webflow.OpenApiClient.Forms.FormsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The pages property</summary>
        public global::Soenneker.Webflow.OpenApiClient.Pages.PagesRequestBuilder Pages
        {
            get => new global::Soenneker.Webflow.OpenApiClient.Pages.PagesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The sites property</summary>
        public global::Soenneker.Webflow.OpenApiClient.Sites.SitesRequestBuilder Sites
        {
            get => new global::Soenneker.Webflow.OpenApiClient.Sites.SitesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The token property</summary>
        public global::Soenneker.Webflow.OpenApiClient.Token.TokenRequestBuilder Token
        {
            get => new global::Soenneker.Webflow.OpenApiClient.Token.TokenRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The webhooks property</summary>
        public global::Soenneker.Webflow.OpenApiClient.Webhooks.WebhooksRequestBuilder Webhooks
        {
            get => new global::Soenneker.Webflow.OpenApiClient.Webhooks.WebhooksRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The workspaces property</summary>
        public global::Soenneker.Webflow.OpenApiClient.Workspaces.WorkspacesRequestBuilder Workspaces
        {
            get => new global::Soenneker.Webflow.OpenApiClient.Workspaces.WorkspacesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Webflow.OpenApiClient.WebflowOpenApiClient"/> and sets the default values.
        /// </summary>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WebflowOpenApiClient(IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}", new Dictionary<string, object>())
        {
            ApiClientBuilder.RegisterDefaultSerializer<JsonSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<TextSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<FormSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<MultipartSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<JsonParseNodeFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<TextParseNodeFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<FormParseNodeFactory>();
            if (string.IsNullOrEmpty(RequestAdapter.BaseUrl))
            {
                RequestAdapter.BaseUrl = "https://api.webflow.com/v2";
            }
            PathParameters.TryAdd("baseurl", RequestAdapter.BaseUrl);
        }
    }
}
#pragma warning restore CS0618
