// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Webflow.OpenApiClient.Sites.Item.Integrations.Google_tags;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Webflow.OpenApiClient.Sites.Item.Integrations
{
    /// <summary>
    /// Builds and executes requests for operations under \sites\{siteId}\integrations
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class IntegrationsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The google_tags property</summary>
        public global::Soenneker.Webflow.OpenApiClient.Sites.Item.Integrations.Google_tags.Google_tagsRequestBuilder Google_tags
        {
            get => new global::Soenneker.Webflow.OpenApiClient.Sites.Item.Integrations.Google_tags.Google_tagsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Webflow.OpenApiClient.Sites.Item.Integrations.IntegrationsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public IntegrationsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/sites/{siteId}/integrations", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Webflow.OpenApiClient.Sites.Item.Integrations.IntegrationsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public IntegrationsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/sites/{siteId}/integrations", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
