// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Webflow.OpenApiClient.Sites.Item.Forms.Item.Submissions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Webflow.OpenApiClient.Sites.Item.Forms.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \sites\{siteId}\forms\{formId}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithFormItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The submissions property</summary>
        public global::Soenneker.Webflow.OpenApiClient.Sites.Item.Forms.Item.Submissions.SubmissionsRequestBuilder Submissions
        {
            get => new global::Soenneker.Webflow.OpenApiClient.Sites.Item.Forms.Item.Submissions.SubmissionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Webflow.OpenApiClient.Sites.Item.Forms.Item.WithFormItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithFormItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/sites/{siteId}/forms/{formId}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Webflow.OpenApiClient.Sites.Item.Forms.Item.WithFormItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithFormItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/sites/{siteId}/forms/{formId}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
