// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Webflow.OpenApiClient.Models;
using Soenneker.Webflow.OpenApiClient.Sites.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Webflow.OpenApiClient.Sites
{
    /// <summary>
    /// Builds and executes requests for operations under \sites
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SitesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.Webflow.OpenApiClient.sites.item collection</summary>
        /// <param name="position">Unique identifier for a Site</param>
        /// <returns>A <see cref="global::Soenneker.Webflow.OpenApiClient.Sites.Item.WithSiteItemRequestBuilder"/></returns>
        public global::Soenneker.Webflow.OpenApiClient.Sites.Item.WithSiteItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("siteId", position);
                return new global::Soenneker.Webflow.OpenApiClient.Sites.Item.WithSiteItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Webflow.OpenApiClient.Sites.SitesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SitesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/sites", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Webflow.OpenApiClient.Sites.SitesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SitesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/sites", rawUrl)
        {
        }
        /// <summary>
        /// List of all sites the provided access token is able to access.Required scope | `sites:read`
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Webflow.OpenApiClient.Models.ListSites200Response"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Webflow.OpenApiClient.Models.ListSites401Response">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Webflow.OpenApiClient.Models.ListSites404Response">When receiving a 404 status code</exception>
        /// <exception cref="global::Soenneker.Webflow.OpenApiClient.Models.ListSites429Response">When receiving a 429 status code</exception>
        /// <exception cref="global::Soenneker.Webflow.OpenApiClient.Models.ListSites4XxResponse">When receiving a 4XX status code</exception>
        /// <exception cref="global::Soenneker.Webflow.OpenApiClient.Models.ListSites5XxResponse">When receiving a 5XX status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Webflow.OpenApiClient.Models.ListSites200Response?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Webflow.OpenApiClient.Models.ListSites200Response> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "401", global::Soenneker.Webflow.OpenApiClient.Models.ListSites401Response.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.Webflow.OpenApiClient.Models.ListSites404Response.CreateFromDiscriminatorValue },
                { "429", global::Soenneker.Webflow.OpenApiClient.Models.ListSites429Response.CreateFromDiscriminatorValue },
                { "4XX", global::Soenneker.Webflow.OpenApiClient.Models.ListSites4XxResponse.CreateFromDiscriminatorValue },
                { "5XX", global::Soenneker.Webflow.OpenApiClient.Models.ListSites5XxResponse.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Webflow.OpenApiClient.Models.ListSites200Response>(requestInfo, global::Soenneker.Webflow.OpenApiClient.Models.ListSites200Response.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// List of all sites the provided access token is able to access.Required scope | `sites:read`
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Webflow.OpenApiClient.Sites.SitesRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Webflow.OpenApiClient.Sites.SitesRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Webflow.OpenApiClient.Sites.SitesRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#pragma warning restore CS0618
