// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Webflow.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Webflow.OpenApiClient.Sites.Item.Analyze.Reports.Top_dimensions
{
    /// <summary>
    /// Builds and executes requests for operations under \sites\{siteId}\analyze\reports\top_dimensions
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Top_dimensionsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Webflow.OpenApiClient.Sites.Item.Analyze.Reports.Top_dimensions.Top_dimensionsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Top_dimensionsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/sites/{siteId}/analyze/reports/top_dimensions?dimension={dimension}&endTime={endTime}&metricScope={metricScope}&startTime={startTime}{&browser*,country*,deviceType*,filter*,limit*,pagePath*,referrer*,trafficSource*,utmCampaign*,utmMedium*,utmSource*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Webflow.OpenApiClient.Sites.Item.Analyze.Reports.Top_dimensions.Top_dimensionsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Top_dimensionsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/sites/{siteId}/analyze/reports/top_dimensions?dimension={dimension}&endTime={endTime}&metricScope={metricScope}&startTime={startTime}{&browser*,country*,deviceType*,filter*,limit*,pagePath*,referrer*,trafficSource*,utmCampaign*,utmMedium*,utmSource*}", rawUrl)
        {
        }
        /// <summary>
        /// Returns the top values within a chosen `dimension` — top countries, top traffic sources, top campaigns, top audiences, and so on — over a time window, ranked by sessions or users.Filter the report with top-level query parameters (`country`, `deviceType`, `pagePath`, etc.) or via the `filter` parameter for multi-value and negation matching.&lt;Warning title=&quot;Analyze add-on required&quot;&gt;This endpoint requires a workspace with the Analyze add-on.&lt;/Warning&gt;&lt;Note title=&quot;Concurrency limit: 1 request at a time&quot;&gt;Each access token can have one Analyze request in flight at a time, across all Analyze endpoints. Additional concurrent requests return `429 Too Many Requests`; wait for your in-flight request to finish, or for the `Retry-After` interval, then retry.&lt;/Note&gt;Required scope | `sites:read`
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200Response"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport400Response">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport401Response">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport403Response">When receiving a 403 status code</exception>
        /// <exception cref="global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport404Response">When receiving a 404 status code</exception>
        /// <exception cref="global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport429Response">When receiving a 429 status code</exception>
        /// <exception cref="global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport500Response">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200Response?> GetAsync(Action<RequestConfiguration<global::Soenneker.Webflow.OpenApiClient.Sites.Item.Analyze.Reports.Top_dimensions.Top_dimensionsRequestBuilder.Top_dimensionsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200Response> GetAsync(Action<RequestConfiguration<global::Soenneker.Webflow.OpenApiClient.Sites.Item.Analyze.Reports.Top_dimensions.Top_dimensionsRequestBuilder.Top_dimensionsRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport400Response.CreateFromDiscriminatorValue },
                { "401", global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport401Response.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport403Response.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport404Response.CreateFromDiscriminatorValue },
                { "429", global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport429Response.CreateFromDiscriminatorValue },
                { "500", global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport500Response.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200Response>(requestInfo, global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200Response.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Returns the top values within a chosen `dimension` — top countries, top traffic sources, top campaigns, top audiences, and so on — over a time window, ranked by sessions or users.Filter the report with top-level query parameters (`country`, `deviceType`, `pagePath`, etc.) or via the `filter` parameter for multi-value and negation matching.&lt;Warning title=&quot;Analyze add-on required&quot;&gt;This endpoint requires a workspace with the Analyze add-on.&lt;/Warning&gt;&lt;Note title=&quot;Concurrency limit: 1 request at a time&quot;&gt;Each access token can have one Analyze request in flight at a time, across all Analyze endpoints. Additional concurrent requests return `429 Too Many Requests`; wait for your in-flight request to finish, or for the `Retry-After` interval, then retry.&lt;/Note&gt;Required scope | `sites:read`
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Webflow.OpenApiClient.Sites.Item.Analyze.Reports.Top_dimensions.Top_dimensionsRequestBuilder.Top_dimensionsRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Webflow.OpenApiClient.Sites.Item.Analyze.Reports.Top_dimensions.Top_dimensionsRequestBuilder.Top_dimensionsRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Webflow.OpenApiClient.Sites.Item.Analyze.Reports.Top_dimensions.Top_dimensionsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Webflow.OpenApiClient.Sites.Item.Analyze.Reports.Top_dimensions.Top_dimensionsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Webflow.OpenApiClient.Sites.Item.Analyze.Reports.Top_dimensions.Top_dimensionsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Returns the top values within a chosen `dimension` — top countries, top traffic sources, top campaigns, top audiences, and so on — over a time window, ranked by sessions or users.Filter the report with top-level query parameters (`country`, `deviceType`, `pagePath`, etc.) or via the `filter` parameter for multi-value and negation matching.&lt;Warning title=&quot;Analyze add-on required&quot;&gt;This endpoint requires a workspace with the Analyze add-on.&lt;/Warning&gt;&lt;Note title=&quot;Concurrency limit: 1 request at a time&quot;&gt;Each access token can have one Analyze request in flight at a time, across all Analyze endpoints. Additional concurrent requests return `429 Too Many Requests`; wait for your in-flight request to finish, or for the `Retry-After` interval, then retry.&lt;/Note&gt;Required scope | `sites:read`
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class Top_dimensionsRequestBuilderGetQueryParameters 
        {
            /// <summary>Restrict the report to a single browser.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("browser")]
            public string? Browser { get; set; }
#nullable restore
#else
            [QueryParameter("browser")]
            public string Browser { get; set; }
#endif
            /// <summary>Restrict the report to a single country. ISO 3166-1 alpha-2 (two letters, normalized to uppercase).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("country")]
            public string? Country { get; set; }
#nullable restore
#else
            [QueryParameter("country")]
            public string Country { get; set; }
#endif
            /// <summary>Restrict the report to a single device type.</summary>
            [QueryParameter("deviceType")]
            public global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReportDeviceTypeParameter? DeviceType { get; set; }
            /// <summary>The dimension whose top values are ranked. See `TopDimensionsDimension` for the supported values.</summary>
            [QueryParameter("dimension")]
            public global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReportDimensionParameter? Dimension { get; set; }
            /// <summary>Exclusive end of the reporting window. Must be a UTC timestamp in ISO 8601 / RFC 3339 format ending in `Z` (for example, `2026-04-08T00:00:00Z`); numeric offsets such as `-04:00` or `+00:00` are not accepted. Must be greater than `startTime` and within 100 days of it.</summary>
            [QueryParameter("endTime")]
            public DateTimeOffset? EndTime { get; set; }
            /// <summary>Filter the report by dimension. Use bracket notation. Scalars take a single value (`filter[country][eq]=US`, `filter[country][ne]=US`). Arrays use indexed brackets (`filter[country][in][0]=US&amp;filter[country][in][1]=CA`, `filter[country][nin][0]=US&amp;filter[country][nin][1]=CA`).Each dimension entry takes at least one of `eq`, `in`, `ne`, or `nin`. Filter a given dimension in one place — either a top-level query parameter or a `filter` entry. See the `TopDimensionsFilter` schema for the full list of supported dimensions.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("filter")]
            public string? Filter { get; set; }
#nullable restore
#else
            [QueryParameter("filter")]
            public string Filter { get; set; }
#endif
            /// <summary>Maximum number of rows to return. Defaults to `25`, up to a maximum of `100`.</summary>
            [QueryParameter("limit")]
            public int? Limit { get; set; }
            /// <summary>The unit each row&apos;s `count` is measured in — sessions or users.</summary>
            [QueryParameter("metricScope")]
            public global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReportMetricScopeParameter? MetricScope { get; set; }
            /// <summary>Restrict the report to a single page path.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("pagePath")]
            public string? PagePath { get; set; }
#nullable restore
#else
            [QueryParameter("pagePath")]
            public string PagePath { get; set; }
#endif
            /// <summary>Restrict the report to a single referrer domain.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("referrer")]
            public string? Referrer { get; set; }
#nullable restore
#else
            [QueryParameter("referrer")]
            public string Referrer { get; set; }
#endif
            /// <summary>Inclusive start of the reporting window. Must be a UTC timestamp in ISO 8601 / RFC 3339 format ending in `Z` (for example, `2026-04-01T00:00:00Z`); numeric offsets such as `-04:00` or `+00:00` are not accepted. Must be on or after `2025-04-09T00:00:00Z`.</summary>
            [QueryParameter("startTime")]
            public DateTimeOffset? StartTime { get; set; }
            /// <summary>Restrict the report to a single traffic source code (for example, `SO` for Organic Search).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("trafficSource")]
            public string? TrafficSource { get; set; }
#nullable restore
#else
            [QueryParameter("trafficSource")]
            public string TrafficSource { get; set; }
#endif
            /// <summary>Restrict the report to a single `utm_campaign` value.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("utmCampaign")]
            public string? UtmCampaign { get; set; }
#nullable restore
#else
            [QueryParameter("utmCampaign")]
            public string UtmCampaign { get; set; }
#endif
            /// <summary>Restrict the report to a single `utm_medium` value.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("utmMedium")]
            public string? UtmMedium { get; set; }
#nullable restore
#else
            [QueryParameter("utmMedium")]
            public string UtmMedium { get; set; }
#endif
            /// <summary>Restrict the report to a single `utm_source` value.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("utmSource")]
            public string? UtmSource { get; set; }
#nullable restore
#else
            [QueryParameter("utmSource")]
            public string UtmSource { get; set; }
#endif
        }
    }
}
#pragma warning restore CS0618
