// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Webflow.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Webflow.OpenApiClient.Collections.Item.Items.Item.Live
{
    /// <summary>
    /// Builds and executes requests for operations under \collections\{collection-id}\items\{item-id}\live
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class LiveRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Webflow.OpenApiClient.Collections.Item.Items.Item.Live.LiveRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public LiveRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/collections/{collection%2Did}/items/{item%2Did}/live{?cmsLocaleId*,skipInvalidFiles*,translatable*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Webflow.OpenApiClient.Collections.Item.Items.Item.Live.LiveRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public LiveRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/collections/{collection%2Did}/items/{item%2Did}/live{?cmsLocaleId*,skipInvalidFiles*,translatable*}", rawUrl)
        {
        }
        /// <summary>
        /// Unpublish a live item from the site and set the `isDraft` property to `true`.For bulk unpublishing, please use [this endpoint.](/data/v2.0.0/reference/cms/collection-items/live-items/delete-items-live)Required scope | `CMS:write`
        /// </summary>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Webflow.OpenApiClient.Models.DeleteItemLive400Response">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Webflow.OpenApiClient.Models.DeleteItemLive401Response">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Webflow.OpenApiClient.Models.DeleteItemLive404Response">When receiving a 404 status code</exception>
        /// <exception cref="global::Soenneker.Webflow.OpenApiClient.Models.DeleteItemLive429Response">When receiving a 429 status code</exception>
        /// <exception cref="global::Soenneker.Webflow.OpenApiClient.Models.DeleteItemLive500Response">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task DeleteAsync(Action<RequestConfiguration<global::Soenneker.Webflow.OpenApiClient.Collections.Item.Items.Item.Live.LiveRequestBuilder.LiveRequestBuilderDeleteQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task DeleteAsync(Action<RequestConfiguration<global::Soenneker.Webflow.OpenApiClient.Collections.Item.Items.Item.Live.LiveRequestBuilder.LiveRequestBuilderDeleteQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToDeleteRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Webflow.OpenApiClient.Models.DeleteItemLive400Response.CreateFromDiscriminatorValue },
                { "401", global::Soenneker.Webflow.OpenApiClient.Models.DeleteItemLive401Response.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.Webflow.OpenApiClient.Models.DeleteItemLive404Response.CreateFromDiscriminatorValue },
                { "429", global::Soenneker.Webflow.OpenApiClient.Models.DeleteItemLive429Response.CreateFromDiscriminatorValue },
                { "500", global::Soenneker.Webflow.OpenApiClient.Models.DeleteItemLive500Response.CreateFromDiscriminatorValue },
            };
            await RequestAdapter.SendNoContentAsync(requestInfo, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Get details of a selected Collection live Item.&lt;Tip title=&quot;Serve data with the Content Delivery API&quot;&gt;  Serving data to applications in real-time? Use the Content Delivery API at `api-cdn.webflow.com` for better performance. The CDN-backed endpoint is optimized for high-volume reads, while the Data API is designed for writes and management operations.&lt;/Tip&gt;Required scope | `CMS:read`
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Webflow.OpenApiClient.Models.GetItemLive200Response"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Webflow.OpenApiClient.Models.GetItemLive400Response">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Webflow.OpenApiClient.Models.GetItemLive401Response">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Webflow.OpenApiClient.Models.GetItemLive404Response">When receiving a 404 status code</exception>
        /// <exception cref="global::Soenneker.Webflow.OpenApiClient.Models.GetItemLive429Response">When receiving a 429 status code</exception>
        /// <exception cref="global::Soenneker.Webflow.OpenApiClient.Models.GetItemLive500Response">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Webflow.OpenApiClient.Models.GetItemLive200Response?> GetAsync(Action<RequestConfiguration<global::Soenneker.Webflow.OpenApiClient.Collections.Item.Items.Item.Live.LiveRequestBuilder.LiveRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Webflow.OpenApiClient.Models.GetItemLive200Response> GetAsync(Action<RequestConfiguration<global::Soenneker.Webflow.OpenApiClient.Collections.Item.Items.Item.Live.LiveRequestBuilder.LiveRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Webflow.OpenApiClient.Models.GetItemLive400Response.CreateFromDiscriminatorValue },
                { "401", global::Soenneker.Webflow.OpenApiClient.Models.GetItemLive401Response.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.Webflow.OpenApiClient.Models.GetItemLive404Response.CreateFromDiscriminatorValue },
                { "429", global::Soenneker.Webflow.OpenApiClient.Models.GetItemLive429Response.CreateFromDiscriminatorValue },
                { "500", global::Soenneker.Webflow.OpenApiClient.Models.GetItemLive500Response.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Webflow.OpenApiClient.Models.GetItemLive200Response>(requestInfo, global::Soenneker.Webflow.OpenApiClient.Models.GetItemLive200Response.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Update a selected live Item in a Collection. The updates for this Item will be published to the live site.Required scope | `CMS:write`
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Webflow.OpenApiClient.Models.UpdateItemLive200Response"/></returns>
        /// <param name="body">The fields that define the schema for a given Item are based on the Collection that Item belongs to. Beyond the user defined fields, there are a handful of additional fields that are automatically created for all items</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Webflow.OpenApiClient.Models.UpdateItemLive400Response">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Webflow.OpenApiClient.Models.UpdateItemLive401Response">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Webflow.OpenApiClient.Models.UpdateItemLive404Response">When receiving a 404 status code</exception>
        /// <exception cref="global::Soenneker.Webflow.OpenApiClient.Models.UpdateItemLive409Response">When receiving a 409 status code</exception>
        /// <exception cref="global::Soenneker.Webflow.OpenApiClient.Models.UpdateItemLive429Response">When receiving a 429 status code</exception>
        /// <exception cref="global::Soenneker.Webflow.OpenApiClient.Models.UpdateItemLive500Response">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Webflow.OpenApiClient.Models.UpdateItemLive200Response?> PatchAsync(global::Soenneker.Webflow.OpenApiClient.Models.UpdateItemLiveRequest body, Action<RequestConfiguration<global::Soenneker.Webflow.OpenApiClient.Collections.Item.Items.Item.Live.LiveRequestBuilder.LiveRequestBuilderPatchQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Webflow.OpenApiClient.Models.UpdateItemLive200Response> PatchAsync(global::Soenneker.Webflow.OpenApiClient.Models.UpdateItemLiveRequest body, Action<RequestConfiguration<global::Soenneker.Webflow.OpenApiClient.Collections.Item.Items.Item.Live.LiveRequestBuilder.LiveRequestBuilderPatchQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPatchRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Webflow.OpenApiClient.Models.UpdateItemLive400Response.CreateFromDiscriminatorValue },
                { "401", global::Soenneker.Webflow.OpenApiClient.Models.UpdateItemLive401Response.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.Webflow.OpenApiClient.Models.UpdateItemLive404Response.CreateFromDiscriminatorValue },
                { "409", global::Soenneker.Webflow.OpenApiClient.Models.UpdateItemLive409Response.CreateFromDiscriminatorValue },
                { "429", global::Soenneker.Webflow.OpenApiClient.Models.UpdateItemLive429Response.CreateFromDiscriminatorValue },
                { "500", global::Soenneker.Webflow.OpenApiClient.Models.UpdateItemLive500Response.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Webflow.OpenApiClient.Models.UpdateItemLive200Response>(requestInfo, global::Soenneker.Webflow.OpenApiClient.Models.UpdateItemLive200Response.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Unpublish a live item from the site and set the `isDraft` property to `true`.For bulk unpublishing, please use [this endpoint.](/data/v2.0.0/reference/cms/collection-items/live-items/delete-items-live)Required scope | `CMS:write`
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<global::Soenneker.Webflow.OpenApiClient.Collections.Item.Items.Item.Live.LiveRequestBuilder.LiveRequestBuilderDeleteQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<global::Soenneker.Webflow.OpenApiClient.Collections.Item.Items.Item.Live.LiveRequestBuilder.LiveRequestBuilderDeleteQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.DELETE, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Get details of a selected Collection live Item.&lt;Tip title=&quot;Serve data with the Content Delivery API&quot;&gt;  Serving data to applications in real-time? Use the Content Delivery API at `api-cdn.webflow.com` for better performance. The CDN-backed endpoint is optimized for high-volume reads, while the Data API is designed for writes and management operations.&lt;/Tip&gt;Required scope | `CMS:read`
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Webflow.OpenApiClient.Collections.Item.Items.Item.Live.LiveRequestBuilder.LiveRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Webflow.OpenApiClient.Collections.Item.Items.Item.Live.LiveRequestBuilder.LiveRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Update a selected live Item in a Collection. The updates for this Item will be published to the live site.Required scope | `CMS:write`
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The fields that define the schema for a given Item are based on the Collection that Item belongs to. Beyond the user defined fields, there are a handful of additional fields that are automatically created for all items</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPatchRequestInformation(global::Soenneker.Webflow.OpenApiClient.Models.UpdateItemLiveRequest body, Action<RequestConfiguration<global::Soenneker.Webflow.OpenApiClient.Collections.Item.Items.Item.Live.LiveRequestBuilder.LiveRequestBuilderPatchQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPatchRequestInformation(global::Soenneker.Webflow.OpenApiClient.Models.UpdateItemLiveRequest body, Action<RequestConfiguration<global::Soenneker.Webflow.OpenApiClient.Collections.Item.Items.Item.Live.LiveRequestBuilder.LiveRequestBuilderPatchQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.PATCH, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Webflow.OpenApiClient.Collections.Item.Items.Item.Live.LiveRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Webflow.OpenApiClient.Collections.Item.Items.Item.Live.LiveRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Webflow.OpenApiClient.Collections.Item.Items.Item.Live.LiveRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Unpublish a live item from the site and set the `isDraft` property to `true`.For bulk unpublishing, please use [this endpoint.](/data/v2.0.0/reference/cms/collection-items/live-items/delete-items-live)Required scope | `CMS:write`
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class LiveRequestBuilderDeleteQueryParameters 
        {
            /// <summary>Unique identifier for a CMS Locale. This UID is different from the Site locale identifier and is listed as `cmsLocaleId` in the Sites response. To query multiple locales, input a comma separated string.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("cmsLocaleId")]
            public string? CmsLocaleId { get; set; }
#nullable restore
#else
            [QueryParameter("cmsLocaleId")]
            public string CmsLocaleId { get; set; }
#endif
        }
        /// <summary>
        /// Get details of a selected Collection live Item.&lt;Tip title=&quot;Serve data with the Content Delivery API&quot;&gt;  Serving data to applications in real-time? Use the Content Delivery API at `api-cdn.webflow.com` for better performance. The CDN-backed endpoint is optimized for high-volume reads, while the Data API is designed for writes and management operations.&lt;/Tip&gt;Required scope | `CMS:read`
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class LiveRequestBuilderGetQueryParameters 
        {
            /// <summary>Unique identifier for a CMS Locale. This UID is different from the Site locale identifier and is listed as `cmsLocaleId` in the Sites response. This endpoint returns a single item, so it accepts one locale. To retrieve an item in several locales, use [List Collection Items](/data/reference/cms/collection-items/staged-items/list-items) with `filter[id][eq]` and a comma separated `cmsLocaleId`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("cmsLocaleId")]
            public string? CmsLocaleId { get; set; }
#nullable restore
#else
            [QueryParameter("cmsLocaleId")]
            public string CmsLocaleId { get; set; }
#endif
            /// <summary>Unique identifier for the secondary Locale you&apos;re translating **into**. Returns only content that hasn&apos;t been excluded from translation for that locale.This is independent of `localeId`, which selects which version of the content is returned. To fetch the source text to translate, request the primary locale&apos;s content and set `translatable` to the locale you&apos;re translating into:`?localeId={primary locale id}&amp;translatable={target locale id}`Only exclusion rules scoped to manual translation are respected — rules scoped only to automatic translation don&apos;t affect this parameter&apos;s response.Omitting `translatable` returns the same response as if this parameter didn&apos;t exist. The value must be the id of one of the site&apos;s secondary locales — the primary locale id, or any other value, returns a `400` error. Requires translation exclusions to be enabled for the site; if they aren&apos;t, the request returns a `403` error.[Learn more about localization.](/data/v2.0.0/docs/working-with-localization)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("translatable")]
            public string? Translatable { get; set; }
#nullable restore
#else
            [QueryParameter("translatable")]
            public string Translatable { get; set; }
#endif
        }
        /// <summary>
        /// Update a selected live Item in a Collection. The updates for this Item will be published to the live site.Required scope | `CMS:write`
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class LiveRequestBuilderPatchQueryParameters 
        {
            /// <summary>When true, invalid files are skipped and processing continues. When false, the entire request fails if any file is invalid.</summary>
            [QueryParameter("skipInvalidFiles")]
            public bool? SkipInvalidFiles { get; set; }
        }
    }
}
#pragma warning restore CS0618
