// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Webflow.OpenApiClient.Workspaces.Item.Audit_logs;
using Soenneker.Webflow.OpenApiClient.Workspaces.Item.Sites;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Webflow.OpenApiClient.Workspaces.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \workspaces\{workspaceIdOrSlug-id}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WorkspaceIdOrSlugItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The audit_logs property</summary>
        public global::Soenneker.Webflow.OpenApiClient.Workspaces.Item.Audit_logs.Audit_logsRequestBuilder Audit_logs
        {
            get => new global::Soenneker.Webflow.OpenApiClient.Workspaces.Item.Audit_logs.Audit_logsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The sites property</summary>
        public global::Soenneker.Webflow.OpenApiClient.Workspaces.Item.Sites.SitesRequestBuilder Sites
        {
            get => new global::Soenneker.Webflow.OpenApiClient.Workspaces.Item.Sites.SitesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Webflow.OpenApiClient.Workspaces.Item.WorkspaceIdOrSlugItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WorkspaceIdOrSlugItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/workspaces/{workspaceIdOrSlug%2Did}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Webflow.OpenApiClient.Workspaces.Item.WorkspaceIdOrSlugItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WorkspaceIdOrSlugItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/workspaces/{workspaceIdOrSlug%2Did}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
