// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Webflow.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum AiToggleSetting
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "ai_toggle")]
        #pragma warning disable CS1591
        AiToggle,
        #pragma warning restore CS1591
    }
}
