// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Webflow.OpenApiClient.Models
{
    /// <summary>
    /// A custom font uploaded to a Webflow site
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class BatchCreateCustomFonts200ResponseCreatedItemCustomFont : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Variable font axes. An empty array indicates a static font.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Webflow.OpenApiClient.Models.BatchCreateCustomFonts200ResponseCreatedItemCustomFontAxesItem>? Axes { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Webflow.OpenApiClient.Models.BatchCreateCustomFonts200ResponseCreatedItemCustomFontAxesItem> Axes { get; set; }
#endif
        /// <summary>The file name supplied at upload time</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FileName { get; private set; }
#nullable restore
#else
        public string FileName { get; private set; }
#endif
        /// <summary>The CSS font-display value</summary>
        public global::Soenneker.Webflow.OpenApiClient.Models.BatchCreateCustomFonts200ResponseCreatedItemCustomFontFontDisplay? FontDisplay { get; set; }
        /// <summary>The CSS font-family name. Commas are stripped server-side.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FontFamily { get; set; }
#nullable restore
#else
        public string FontFamily { get; set; }
#endif
        /// <summary>The font file format, derived from the file extension. The value `svg` represents read-only legacy data; new SVG font uploads are not accepted.</summary>
        public global::Soenneker.Webflow.OpenApiClient.Models.BatchCreateCustomFonts200ResponseCreatedItemCustomFontFormat? Format { get; private set; }
        /// <summary>CDN URL for the font binary</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? HostedUrl { get; private set; }
#nullable restore
#else
        public string HostedUrl { get; private set; }
#endif
        /// <summary>Unique identifier for the custom font</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; private set; }
#nullable restore
#else
        public string Id { get; private set; }
#endif
        /// <summary>Whether the font is italic</summary>
        public bool? Italic { get; set; }
        /// <summary>The CSS font-weight value (1–1000)</summary>
        public int? Weight { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Webflow.OpenApiClient.Models.BatchCreateCustomFonts200ResponseCreatedItemCustomFont"/> and sets the default values.
        /// </summary>
        public BatchCreateCustomFonts200ResponseCreatedItemCustomFont()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Webflow.OpenApiClient.Models.BatchCreateCustomFonts200ResponseCreatedItemCustomFont"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Webflow.OpenApiClient.Models.BatchCreateCustomFonts200ResponseCreatedItemCustomFont CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Webflow.OpenApiClient.Models.BatchCreateCustomFonts200ResponseCreatedItemCustomFont();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "axes", n => { Axes = n.GetCollectionOfObjectValues<global::Soenneker.Webflow.OpenApiClient.Models.BatchCreateCustomFonts200ResponseCreatedItemCustomFontAxesItem>(global::Soenneker.Webflow.OpenApiClient.Models.BatchCreateCustomFonts200ResponseCreatedItemCustomFontAxesItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "fileName", n => { FileName = n.GetStringValue(); } },
                { "fontDisplay", n => { FontDisplay = n.GetEnumValue<global::Soenneker.Webflow.OpenApiClient.Models.BatchCreateCustomFonts200ResponseCreatedItemCustomFontFontDisplay>(); } },
                { "fontFamily", n => { FontFamily = n.GetStringValue(); } },
                { "format", n => { Format = n.GetEnumValue<global::Soenneker.Webflow.OpenApiClient.Models.BatchCreateCustomFonts200ResponseCreatedItemCustomFontFormat>(); } },
                { "hostedUrl", n => { HostedUrl = n.GetStringValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "italic", n => { Italic = n.GetBoolValue(); } },
                { "weight", n => { Weight = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Soenneker.Webflow.OpenApiClient.Models.BatchCreateCustomFonts200ResponseCreatedItemCustomFontAxesItem>("axes", Axes);
            writer.WriteEnumValue<global::Soenneker.Webflow.OpenApiClient.Models.BatchCreateCustomFonts200ResponseCreatedItemCustomFontFontDisplay>("fontDisplay", FontDisplay);
            writer.WriteStringValue("fontFamily", FontFamily);
            writer.WriteBoolValue("italic", Italic);
            writer.WriteIntValue("weight", Weight);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
