// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Webflow.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CollectionItemCreatedRequestPayload : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Unique identifier of the CMS locale for this item</summary>
        public Guid? CmsLocaleId { get; set; }
        /// <summary>Unique identifier of the collection</summary>
        public Guid? CollectionId { get; set; }
        /// <summary>The createdOn property</summary>
        public DateTimeOffset? CreatedOn { get; set; }
        /// <summary>The fieldData property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Webflow.OpenApiClient.Models.CollectionItemCreatedRequestPayloadFieldData? FieldData { get; set; }
#nullable restore
#else
        public global::Soenneker.Webflow.OpenApiClient.Models.CollectionItemCreatedRequestPayloadFieldData FieldData { get; set; }
#endif
        /// <summary>Unique identifier for the Item</summary>
        public Guid? Id { get; set; }
        /// <summary>The isArchived property</summary>
        public bool? IsArchived { get; set; }
        /// <summary>The isDraft property</summary>
        public bool? IsDraft { get; set; }
        /// <summary>The lastPublished property</summary>
        public DateTimeOffset? LastPublished { get; set; }
        /// <summary>The lastUpdated property</summary>
        public DateTimeOffset? LastUpdated { get; set; }
        /// <summary>Unique identifier of the site</summary>
        public Guid? SiteId { get; set; }
        /// <summary>Unique identifier of the workspace</summary>
        public Guid? WorkspaceId { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Webflow.OpenApiClient.Models.CollectionItemCreatedRequestPayload"/> and sets the default values.
        /// </summary>
        public CollectionItemCreatedRequestPayload()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Webflow.OpenApiClient.Models.CollectionItemCreatedRequestPayload"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Webflow.OpenApiClient.Models.CollectionItemCreatedRequestPayload CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Webflow.OpenApiClient.Models.CollectionItemCreatedRequestPayload();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "cmsLocaleId", n => { CmsLocaleId = n.GetGuidValue(); } },
                { "collectionId", n => { CollectionId = n.GetGuidValue(); } },
                { "createdOn", n => { CreatedOn = n.GetDateTimeOffsetValue(); } },
                { "fieldData", n => { FieldData = n.GetObjectValue<global::Soenneker.Webflow.OpenApiClient.Models.CollectionItemCreatedRequestPayloadFieldData>(global::Soenneker.Webflow.OpenApiClient.Models.CollectionItemCreatedRequestPayloadFieldData.CreateFromDiscriminatorValue); } },
                { "id", n => { Id = n.GetGuidValue(); } },
                { "isArchived", n => { IsArchived = n.GetBoolValue(); } },
                { "isDraft", n => { IsDraft = n.GetBoolValue(); } },
                { "lastPublished", n => { LastPublished = n.GetDateTimeOffsetValue(); } },
                { "lastUpdated", n => { LastUpdated = n.GetDateTimeOffsetValue(); } },
                { "siteId", n => { SiteId = n.GetGuidValue(); } },
                { "workspaceId", n => { WorkspaceId = n.GetGuidValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteGuidValue("cmsLocaleId", CmsLocaleId);
            writer.WriteGuidValue("collectionId", CollectionId);
            writer.WriteDateTimeOffsetValue("createdOn", CreatedOn);
            writer.WriteObjectValue<global::Soenneker.Webflow.OpenApiClient.Models.CollectionItemCreatedRequestPayloadFieldData>("fieldData", FieldData);
            writer.WriteGuidValue("id", Id);
            writer.WriteBoolValue("isArchived", IsArchived);
            writer.WriteBoolValue("isDraft", IsDraft);
            writer.WriteDateTimeOffsetValue("lastPublished", LastPublished);
            writer.WriteDateTimeOffsetValue("lastUpdated", LastUpdated);
            writer.WriteGuidValue("siteId", SiteId);
            writer.WriteGuidValue("workspaceId", WorkspaceId);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
