// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Webflow.OpenApiClient.Models
{
    /// <summary>
    /// Standard and Custom fields for a SKU
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CreateProductRequestSkuFieldData : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>comparison price of SKU</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Webflow.OpenApiClient.Models.CreateProductRequestSkuFieldDataCompareAtPrice? CompareAtPrice { get; set; }
#nullable restore
#else
        public global::Soenneker.Webflow.OpenApiClient.Models.CreateProductRequestSkuFieldDataCompareAtPrice CompareAtPrice { get; set; }
#endif
        /// <summary>[Billing method](https://help.webflow.com/hc/en-us/articles/33961432087955-Add-and-manage-products-and-categories#billing-methods)for the SKU</summary>
        public global::Soenneker.Webflow.OpenApiClient.Models.CreateProductRequestSkuFieldDataEcSkuBillingMethod? EcSkuBillingMethod { get; set; }
        /// <summary>[Subscription plan](https://help.webflow.com/hc/en-us/articles/33961432087955-Add-and-manage-products-and-categories#subscription) for the SKU</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Webflow.OpenApiClient.Models.CreateProductRequestSkuFieldDataEcSkuSubscriptionPlan? EcSkuSubscriptionPlan { get; set; }
#nullable restore
#else
        public global::Soenneker.Webflow.OpenApiClient.Models.CreateProductRequestSkuFieldDataEcSkuSubscriptionPlan EcSkuSubscriptionPlan { get; set; }
#endif
        /// <summary>The URL for the main image of the SKU</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MainImage { get; set; }
#nullable restore
#else
        public string MainImage { get; set; }
#endif
        /// <summary>Name of the Product</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>price of SKU</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Webflow.OpenApiClient.Models.CreateProductRequestSkuFieldDataPrice? Price { get; set; }
#nullable restore
#else
        public global::Soenneker.Webflow.OpenApiClient.Models.CreateProductRequestSkuFieldDataPrice Price { get; set; }
#endif
        /// <summary>A unique identifier for the SKU</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Sku { get; set; }
#nullable restore
#else
        public string Sku { get; set; }
#endif
        /// <summary>The properties of the SKU</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Webflow.OpenApiClient.Models.CreateProductRequestSkuFieldDataSkuPropertiesItem>? SkuProperties { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Webflow.OpenApiClient.Models.CreateProductRequestSkuFieldDataSkuPropertiesItem> SkuProperties { get; set; }
#endif
        /// <summary>A mapping between SKU properties and their values, represented as key-value pairs. Each key represents a SKU Property ID (e.g. &quot;color&quot;) and maps to its corresponding SKU Value ID (e.g. &quot;blue&quot;). This structure defines the specific variant combination for a SKU.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Webflow.OpenApiClient.Models.CreateProductRequestSkuFieldDataSkuValues? SkuValues { get; set; }
#nullable restore
#else
        public global::Soenneker.Webflow.OpenApiClient.Models.CreateProductRequestSkuFieldDataSkuValues SkuValues { get; set; }
#endif
        /// <summary>URL structure of the Product in your site.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Slug { get; set; }
#nullable restore
#else
        public string Slug { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Webflow.OpenApiClient.Models.CreateProductRequestSkuFieldData"/> and sets the default values.
        /// </summary>
        public CreateProductRequestSkuFieldData()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Webflow.OpenApiClient.Models.CreateProductRequestSkuFieldData"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Webflow.OpenApiClient.Models.CreateProductRequestSkuFieldData CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Webflow.OpenApiClient.Models.CreateProductRequestSkuFieldData();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "compare-at-price", n => { CompareAtPrice = n.GetObjectValue<global::Soenneker.Webflow.OpenApiClient.Models.CreateProductRequestSkuFieldDataCompareAtPrice>(global::Soenneker.Webflow.OpenApiClient.Models.CreateProductRequestSkuFieldDataCompareAtPrice.CreateFromDiscriminatorValue); } },
                { "ec-sku-billing-method", n => { EcSkuBillingMethod = n.GetEnumValue<global::Soenneker.Webflow.OpenApiClient.Models.CreateProductRequestSkuFieldDataEcSkuBillingMethod>(); } },
                { "ec-sku-subscription-plan", n => { EcSkuSubscriptionPlan = n.GetObjectValue<global::Soenneker.Webflow.OpenApiClient.Models.CreateProductRequestSkuFieldDataEcSkuSubscriptionPlan>(global::Soenneker.Webflow.OpenApiClient.Models.CreateProductRequestSkuFieldDataEcSkuSubscriptionPlan.CreateFromDiscriminatorValue); } },
                { "main-image", n => { MainImage = n.GetStringValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "price", n => { Price = n.GetObjectValue<global::Soenneker.Webflow.OpenApiClient.Models.CreateProductRequestSkuFieldDataPrice>(global::Soenneker.Webflow.OpenApiClient.Models.CreateProductRequestSkuFieldDataPrice.CreateFromDiscriminatorValue); } },
                { "sku", n => { Sku = n.GetStringValue(); } },
                { "sku-properties", n => { SkuProperties = n.GetCollectionOfObjectValues<global::Soenneker.Webflow.OpenApiClient.Models.CreateProductRequestSkuFieldDataSkuPropertiesItem>(global::Soenneker.Webflow.OpenApiClient.Models.CreateProductRequestSkuFieldDataSkuPropertiesItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "sku-values", n => { SkuValues = n.GetObjectValue<global::Soenneker.Webflow.OpenApiClient.Models.CreateProductRequestSkuFieldDataSkuValues>(global::Soenneker.Webflow.OpenApiClient.Models.CreateProductRequestSkuFieldDataSkuValues.CreateFromDiscriminatorValue); } },
                { "slug", n => { Slug = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Webflow.OpenApiClient.Models.CreateProductRequestSkuFieldDataCompareAtPrice>("compare-at-price", CompareAtPrice);
            writer.WriteEnumValue<global::Soenneker.Webflow.OpenApiClient.Models.CreateProductRequestSkuFieldDataEcSkuBillingMethod>("ec-sku-billing-method", EcSkuBillingMethod);
            writer.WriteObjectValue<global::Soenneker.Webflow.OpenApiClient.Models.CreateProductRequestSkuFieldDataEcSkuSubscriptionPlan>("ec-sku-subscription-plan", EcSkuSubscriptionPlan);
            writer.WriteStringValue("main-image", MainImage);
            writer.WriteStringValue("name", Name);
            writer.WriteObjectValue<global::Soenneker.Webflow.OpenApiClient.Models.CreateProductRequestSkuFieldDataPrice>("price", Price);
            writer.WriteStringValue("sku", Sku);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Webflow.OpenApiClient.Models.CreateProductRequestSkuFieldDataSkuPropertiesItem>("sku-properties", SkuProperties);
            writer.WriteObjectValue<global::Soenneker.Webflow.OpenApiClient.Models.CreateProductRequestSkuFieldDataSkuValues>("sku-values", SkuValues);
            writer.WriteStringValue("slug", Slug);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
