// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Webflow.OpenApiClient.Models
{
    /// <summary>
    /// Information about the custom font to create
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CreateCustomFontRequest : IParsable
    {
        /// <summary>Variable font axes. Omit or pass an empty array for static fonts.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Webflow.OpenApiClient.Models.CreateCustomFontRequestAxesItem>? Axes { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Webflow.OpenApiClient.Models.CreateCustomFontRequestAxesItem> Axes { get; set; }
#endif
        /// <summary>Lowercase hex MD5 hash of the font binary (exactly 32 characters)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FileHash { get; set; }
#nullable restore
#else
        public string FileHash { get; set; }
#endif
        /// <summary>File name including extension. Accepted extensions are `.woff2`, `.woff`, `.ttf`, `.otf`, and `.eot`. Maximum 256 characters.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FileName { get; set; }
#nullable restore
#else
        public string FileName { get; set; }
#endif
        /// <summary>CSS font-display value</summary>
        public global::Soenneker.Webflow.OpenApiClient.Models.CreateCustomFontRequestFontDisplay? FontDisplay { get; set; }
        /// <summary>The CSS font-family name (1-256 characters). Commas are stripped server-side.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FontFamily { get; set; }
#nullable restore
#else
        public string FontFamily { get; set; }
#endif
        /// <summary>Whether the font is italic</summary>
        public bool? Italic { get; set; }
        /// <summary>CSS font-weight value (1-1000)</summary>
        public int? Weight { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Webflow.OpenApiClient.Models.CreateCustomFontRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Webflow.OpenApiClient.Models.CreateCustomFontRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Webflow.OpenApiClient.Models.CreateCustomFontRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "axes", n => { Axes = n.GetCollectionOfObjectValues<global::Soenneker.Webflow.OpenApiClient.Models.CreateCustomFontRequestAxesItem>(global::Soenneker.Webflow.OpenApiClient.Models.CreateCustomFontRequestAxesItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "fileHash", n => { FileHash = n.GetStringValue(); } },
                { "fileName", n => { FileName = n.GetStringValue(); } },
                { "fontDisplay", n => { FontDisplay = n.GetEnumValue<global::Soenneker.Webflow.OpenApiClient.Models.CreateCustomFontRequestFontDisplay>(); } },
                { "fontFamily", n => { FontFamily = n.GetStringValue(); } },
                { "italic", n => { Italic = n.GetBoolValue(); } },
                { "weight", n => { Weight = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Soenneker.Webflow.OpenApiClient.Models.CreateCustomFontRequestAxesItem>("axes", Axes);
            writer.WriteStringValue("fileHash", FileHash);
            writer.WriteStringValue("fileName", FileName);
            writer.WriteEnumValue<global::Soenneker.Webflow.OpenApiClient.Models.CreateCustomFontRequestFontDisplay>("fontDisplay", FontDisplay);
            writer.WriteStringValue("fontFamily", FontFamily);
            writer.WriteBoolValue("italic", Italic);
            writer.WriteIntValue("weight", Weight);
        }
    }
}
#pragma warning restore CS0618
