// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Webflow.OpenApiClient.Models
{
    /// <summary>
    /// An object describing various pricing totals
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class EcommNewOrderRequestPayloadTotals : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>An array of extra items, includes discounts, shipping, and taxes.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Webflow.OpenApiClient.Models.EcommNewOrderRequestPayloadTotalsExtrasItem>? Extras { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Webflow.OpenApiClient.Models.EcommNewOrderRequestPayloadTotalsExtrasItem> Extras { get; set; }
#endif
        /// <summary>The subtotal price</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Webflow.OpenApiClient.Models.EcommNewOrderRequestPayloadTotalsSubtotal? Subtotal { get; set; }
#nullable restore
#else
        public global::Soenneker.Webflow.OpenApiClient.Models.EcommNewOrderRequestPayloadTotalsSubtotal Subtotal { get; set; }
#endif
        /// <summary>The total price</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Webflow.OpenApiClient.Models.EcommNewOrderRequestPayloadTotalsTotal? Total { get; set; }
#nullable restore
#else
        public global::Soenneker.Webflow.OpenApiClient.Models.EcommNewOrderRequestPayloadTotalsTotal Total { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Webflow.OpenApiClient.Models.EcommNewOrderRequestPayloadTotals"/> and sets the default values.
        /// </summary>
        public EcommNewOrderRequestPayloadTotals()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Webflow.OpenApiClient.Models.EcommNewOrderRequestPayloadTotals"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Webflow.OpenApiClient.Models.EcommNewOrderRequestPayloadTotals CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Webflow.OpenApiClient.Models.EcommNewOrderRequestPayloadTotals();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "extras", n => { Extras = n.GetCollectionOfObjectValues<global::Soenneker.Webflow.OpenApiClient.Models.EcommNewOrderRequestPayloadTotalsExtrasItem>(global::Soenneker.Webflow.OpenApiClient.Models.EcommNewOrderRequestPayloadTotalsExtrasItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "subtotal", n => { Subtotal = n.GetObjectValue<global::Soenneker.Webflow.OpenApiClient.Models.EcommNewOrderRequestPayloadTotalsSubtotal>(global::Soenneker.Webflow.OpenApiClient.Models.EcommNewOrderRequestPayloadTotalsSubtotal.CreateFromDiscriminatorValue); } },
                { "total", n => { Total = n.GetObjectValue<global::Soenneker.Webflow.OpenApiClient.Models.EcommNewOrderRequestPayloadTotalsTotal>(global::Soenneker.Webflow.OpenApiClient.Models.EcommNewOrderRequestPayloadTotalsTotal.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Soenneker.Webflow.OpenApiClient.Models.EcommNewOrderRequestPayloadTotalsExtrasItem>("extras", Extras);
            writer.WriteObjectValue<global::Soenneker.Webflow.OpenApiClient.Models.EcommNewOrderRequestPayloadTotalsSubtotal>("subtotal", Subtotal);
            writer.WriteObjectValue<global::Soenneker.Webflow.OpenApiClient.Models.EcommNewOrderRequestPayloadTotalsTotal>("total", Total);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
