// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Webflow.OpenApiClient.Models
{
    /// <summary>The type of extra item this is.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum EcommOrderChangedRequestPayloadTotalsExtrasItemType
    {
        [EnumMember(Value = "discount")]
        #pragma warning disable CS1591
        Discount,
        #pragma warning restore CS1591
        [EnumMember(Value = "discount-shipping")]
        #pragma warning disable CS1591
        DiscountShipping,
        #pragma warning restore CS1591
        [EnumMember(Value = "shipping")]
        #pragma warning disable CS1591
        Shipping,
        #pragma warning restore CS1591
        [EnumMember(Value = "tax")]
        #pragma warning disable CS1591
        Tax,
        #pragma warning restore CS1591
    }
}
