// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Webflow.OpenApiClient.Models
{
    /// <summary>
    /// The payload of data sent from Webflow
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class FormSubmissionRequestPayload : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The data submitted in the form</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Webflow.OpenApiClient.Models.FormSubmissionRequestPayloadData? Data { get; set; }
#nullable restore
#else
        public global::Soenneker.Webflow.OpenApiClient.Models.FormSubmissionRequestPayloadData Data { get; set; }
#endif
        /// <summary>The uniqueID of the Form element</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FormElementId { get; set; }
#nullable restore
#else
        public string FormElementId { get; set; }
#endif
        /// <summary>The ID of the form submission</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FormId { get; set; }
#nullable restore
#else
        public string FormId { get; set; }
#endif
        /// <summary>the ID of the event</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The ID of the locale the form was submitted from. `null` for primary-locale submissions or sites without localization.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LocaleId { get; set; }
#nullable restore
#else
        public string LocaleId { get; set; }
#endif
        /// <summary>The name of the form</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>A list of fields from the submitted form</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Webflow.OpenApiClient.Models.FormSubmissionRequestPayloadSchemaItem>? Schema { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Webflow.OpenApiClient.Models.FormSubmissionRequestPayloadSchemaItem> Schema { get; set; }
#endif
        /// <summary>The ID of the site that the form was submitted from</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SiteId { get; set; }
#nullable restore
#else
        public string SiteId { get; set; }
#endif
        /// <summary>The timestamp the form was submitted</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SubmittedAt { get; set; }
#nullable restore
#else
        public string SubmittedAt { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Webflow.OpenApiClient.Models.FormSubmissionRequestPayload"/> and sets the default values.
        /// </summary>
        public FormSubmissionRequestPayload()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Webflow.OpenApiClient.Models.FormSubmissionRequestPayload"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Webflow.OpenApiClient.Models.FormSubmissionRequestPayload CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Webflow.OpenApiClient.Models.FormSubmissionRequestPayload();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "data", n => { Data = n.GetObjectValue<global::Soenneker.Webflow.OpenApiClient.Models.FormSubmissionRequestPayloadData>(global::Soenneker.Webflow.OpenApiClient.Models.FormSubmissionRequestPayloadData.CreateFromDiscriminatorValue); } },
                { "formElementId", n => { FormElementId = n.GetStringValue(); } },
                { "formId", n => { FormId = n.GetStringValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "localeId", n => { LocaleId = n.GetStringValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "schema", n => { Schema = n.GetCollectionOfObjectValues<global::Soenneker.Webflow.OpenApiClient.Models.FormSubmissionRequestPayloadSchemaItem>(global::Soenneker.Webflow.OpenApiClient.Models.FormSubmissionRequestPayloadSchemaItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "siteId", n => { SiteId = n.GetStringValue(); } },
                { "submittedAt", n => { SubmittedAt = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Webflow.OpenApiClient.Models.FormSubmissionRequestPayloadData>("data", Data);
            writer.WriteStringValue("formElementId", FormElementId);
            writer.WriteStringValue("formId", FormId);
            writer.WriteStringValue("id", Id);
            writer.WriteStringValue("localeId", LocaleId);
            writer.WriteStringValue("name", Name);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Webflow.OpenApiClient.Models.FormSubmissionRequestPayloadSchemaItem>("schema", Schema);
            writer.WriteStringValue("siteId", SiteId);
            writer.WriteStringValue("submittedAt", SubmittedAt);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
