// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Webflow.OpenApiClient.Models
{
    /// <summary>
    /// Filter the top dimensions report by dimension. Each property is an optional set of `AnalyzeFilterOperators` (`eq`, `in`, `ne`, `nin`) applied to the named dimension. Filter a given dimension in one place — either inside `filter` or as a top-level query parameter.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class GetAnalyzeTopDimensionsReport200ResponseFilter : IParsable
    {
        /// <summary>Operators for filtering a single dimension. Specify at least one of `eq`, `in`, `ne`, or `nin`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilterAudienceIds? AudienceIds { get; set; }
#nullable restore
#else
        public global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilterAudienceIds AudienceIds { get; set; }
#endif
        /// <summary>Operators for filtering a single dimension. Specify at least one of `eq`, `in`, `ne`, or `nin`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilterBrowser? Browser { get; set; }
#nullable restore
#else
        public global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilterBrowser Browser { get; set; }
#endif
        /// <summary>Operators for filtering a single dimension. Specify at least one of `eq`, `in`, `ne`, or `nin`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilterCollectionId? CollectionId { get; set; }
#nullable restore
#else
        public global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilterCollectionId CollectionId { get; set; }
#endif
        /// <summary>Operators for filtering a single dimension. Specify at least one of `eq`, `in`, `ne`, or `nin`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilterCountry? Country { get; set; }
#nullable restore
#else
        public global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilterCountry Country { get; set; }
#endif
        /// <summary>Operators for filtering a single dimension. Specify at least one of `eq`, `in`, `ne`, or `nin`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilterDayOfWeek? DayOfWeek { get; set; }
#nullable restore
#else
        public global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilterDayOfWeek DayOfWeek { get; set; }
#endif
        /// <summary>Operators for filtering a single dimension. Specify at least one of `eq`, `in`, `ne`, or `nin`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilterDeviceBrand? DeviceBrand { get; set; }
#nullable restore
#else
        public global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilterDeviceBrand DeviceBrand { get; set; }
#endif
        /// <summary>Operators for filtering a single dimension. Specify at least one of `eq`, `in`, `ne`, or `nin`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilterDeviceType? DeviceType { get; set; }
#nullable restore
#else
        public global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilterDeviceType DeviceType { get; set; }
#endif
        /// <summary>Operators for filtering a single dimension. Specify at least one of `eq`, `in`, `ne`, or `nin`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilterDomain? Domain { get; set; }
#nullable restore
#else
        public global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilterDomain Domain { get; set; }
#endif
        /// <summary>Operators for filtering a single dimension. Specify at least one of `eq`, `in`, `ne`, or `nin`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilterItemSlug? ItemSlug { get; set; }
#nullable restore
#else
        public global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilterItemSlug ItemSlug { get; set; }
#endif
        /// <summary>Operators for filtering a single dimension. Specify at least one of `eq`, `in`, `ne`, or `nin`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilterLanguage? Language { get; set; }
#nullable restore
#else
        public global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilterLanguage Language { get; set; }
#endif
        /// <summary>Operators for filtering a single dimension. Specify at least one of `eq`, `in`, `ne`, or `nin`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilterLocale? Locale { get; set; }
#nullable restore
#else
        public global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilterLocale Locale { get; set; }
#endif
        /// <summary>Operators for filtering a single dimension. Specify at least one of `eq`, `in`, `ne`, or `nin`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilterNextCollectionId? NextCollectionId { get; set; }
#nullable restore
#else
        public global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilterNextCollectionId NextCollectionId { get; set; }
#endif
        /// <summary>Operators for filtering a single dimension. Specify at least one of `eq`, `in`, `ne`, or `nin`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilterNextItemSlug? NextItemSlug { get; set; }
#nullable restore
#else
        public global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilterNextItemSlug NextItemSlug { get; set; }
#endif
        /// <summary>Operators for filtering a single dimension. Specify at least one of `eq`, `in`, `ne`, or `nin`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilterNextPageId? NextPageId { get; set; }
#nullable restore
#else
        public global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilterNextPageId NextPageId { get; set; }
#endif
        /// <summary>Operators for filtering a single dimension. Specify at least one of `eq`, `in`, `ne`, or `nin`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilterOs? Os { get; set; }
#nullable restore
#else
        public global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilterOs Os { get; set; }
#endif
        /// <summary>Operators for filtering a single dimension. Specify at least one of `eq`, `in`, `ne`, or `nin`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilterPageId? PageId { get; set; }
#nullable restore
#else
        public global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilterPageId PageId { get; set; }
#endif
        /// <summary>Operators for filtering a single dimension. Specify at least one of `eq`, `in`, `ne`, or `nin`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilterPagePath? PagePath { get; set; }
#nullable restore
#else
        public global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilterPagePath PagePath { get; set; }
#endif
        /// <summary>Operators for filtering a single dimension. Specify at least one of `eq`, `in`, `ne`, or `nin`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilterPreviousCollectionId? PreviousCollectionId { get; set; }
#nullable restore
#else
        public global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilterPreviousCollectionId PreviousCollectionId { get; set; }
#endif
        /// <summary>Operators for filtering a single dimension. Specify at least one of `eq`, `in`, `ne`, or `nin`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilterPreviousItemSlug? PreviousItemSlug { get; set; }
#nullable restore
#else
        public global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilterPreviousItemSlug PreviousItemSlug { get; set; }
#endif
        /// <summary>Operators for filtering a single dimension. Specify at least one of `eq`, `in`, `ne`, or `nin`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilterPreviousPageId? PreviousPageId { get; set; }
#nullable restore
#else
        public global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilterPreviousPageId PreviousPageId { get; set; }
#endif
        /// <summary>Operators for filtering a single dimension. Specify at least one of `eq`, `in`, `ne`, or `nin`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilterReferrer? Referrer { get; set; }
#nullable restore
#else
        public global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilterReferrer Referrer { get; set; }
#endif
        /// <summary>Operators for filtering a single dimension. Specify at least one of `eq`, `in`, `ne`, or `nin`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilterRegion? Region { get; set; }
#nullable restore
#else
        public global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilterRegion Region { get; set; }
#endif
        /// <summary>Operators for filtering a single dimension. Specify at least one of `eq`, `in`, `ne`, or `nin`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilterTimeOfDay? TimeOfDay { get; set; }
#nullable restore
#else
        public global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilterTimeOfDay TimeOfDay { get; set; }
#endif
        /// <summary>Operators for filtering a single dimension. Specify at least one of `eq`, `in`, `ne`, or `nin`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilterTimezone? Timezone { get; set; }
#nullable restore
#else
        public global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilterTimezone Timezone { get; set; }
#endif
        /// <summary>Operators for filtering a single dimension. Specify at least one of `eq`, `in`, `ne`, or `nin`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilterTrafficSource? TrafficSource { get; set; }
#nullable restore
#else
        public global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilterTrafficSource TrafficSource { get; set; }
#endif
        /// <summary>Operators for filtering a single dimension. Specify at least one of `eq`, `in`, `ne`, or `nin`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilterUtmCampaign? UtmCampaign { get; set; }
#nullable restore
#else
        public global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilterUtmCampaign UtmCampaign { get; set; }
#endif
        /// <summary>Operators for filtering a single dimension. Specify at least one of `eq`, `in`, `ne`, or `nin`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilterUtmContent? UtmContent { get; set; }
#nullable restore
#else
        public global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilterUtmContent UtmContent { get; set; }
#endif
        /// <summary>Operators for filtering a single dimension. Specify at least one of `eq`, `in`, `ne`, or `nin`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilterUtmMedium? UtmMedium { get; set; }
#nullable restore
#else
        public global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilterUtmMedium UtmMedium { get; set; }
#endif
        /// <summary>Operators for filtering a single dimension. Specify at least one of `eq`, `in`, `ne`, or `nin`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilterUtmSource? UtmSource { get; set; }
#nullable restore
#else
        public global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilterUtmSource UtmSource { get; set; }
#endif
        /// <summary>Operators for filtering a single dimension. Specify at least one of `eq`, `in`, `ne`, or `nin`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilterUtmTerm? UtmTerm { get; set; }
#nullable restore
#else
        public global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilterUtmTerm UtmTerm { get; set; }
#endif
        /// <summary>Operators for filtering a single dimension. Specify at least one of `eq`, `in`, `ne`, or `nin`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilterVisitStatus? VisitStatus { get; set; }
#nullable restore
#else
        public global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilterVisitStatus VisitStatus { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilter"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilter CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilter();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "audienceIds", n => { AudienceIds = n.GetObjectValue<global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilterAudienceIds>(global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilterAudienceIds.CreateFromDiscriminatorValue); } },
                { "browser", n => { Browser = n.GetObjectValue<global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilterBrowser>(global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilterBrowser.CreateFromDiscriminatorValue); } },
                { "collectionId", n => { CollectionId = n.GetObjectValue<global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilterCollectionId>(global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilterCollectionId.CreateFromDiscriminatorValue); } },
                { "country", n => { Country = n.GetObjectValue<global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilterCountry>(global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilterCountry.CreateFromDiscriminatorValue); } },
                { "dayOfWeek", n => { DayOfWeek = n.GetObjectValue<global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilterDayOfWeek>(global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilterDayOfWeek.CreateFromDiscriminatorValue); } },
                { "deviceBrand", n => { DeviceBrand = n.GetObjectValue<global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilterDeviceBrand>(global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilterDeviceBrand.CreateFromDiscriminatorValue); } },
                { "deviceType", n => { DeviceType = n.GetObjectValue<global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilterDeviceType>(global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilterDeviceType.CreateFromDiscriminatorValue); } },
                { "domain", n => { Domain = n.GetObjectValue<global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilterDomain>(global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilterDomain.CreateFromDiscriminatorValue); } },
                { "itemSlug", n => { ItemSlug = n.GetObjectValue<global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilterItemSlug>(global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilterItemSlug.CreateFromDiscriminatorValue); } },
                { "language", n => { Language = n.GetObjectValue<global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilterLanguage>(global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilterLanguage.CreateFromDiscriminatorValue); } },
                { "locale", n => { Locale = n.GetObjectValue<global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilterLocale>(global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilterLocale.CreateFromDiscriminatorValue); } },
                { "nextCollectionId", n => { NextCollectionId = n.GetObjectValue<global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilterNextCollectionId>(global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilterNextCollectionId.CreateFromDiscriminatorValue); } },
                { "nextItemSlug", n => { NextItemSlug = n.GetObjectValue<global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilterNextItemSlug>(global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilterNextItemSlug.CreateFromDiscriminatorValue); } },
                { "nextPageId", n => { NextPageId = n.GetObjectValue<global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilterNextPageId>(global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilterNextPageId.CreateFromDiscriminatorValue); } },
                { "os", n => { Os = n.GetObjectValue<global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilterOs>(global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilterOs.CreateFromDiscriminatorValue); } },
                { "pageId", n => { PageId = n.GetObjectValue<global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilterPageId>(global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilterPageId.CreateFromDiscriminatorValue); } },
                { "pagePath", n => { PagePath = n.GetObjectValue<global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilterPagePath>(global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilterPagePath.CreateFromDiscriminatorValue); } },
                { "previousCollectionId", n => { PreviousCollectionId = n.GetObjectValue<global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilterPreviousCollectionId>(global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilterPreviousCollectionId.CreateFromDiscriminatorValue); } },
                { "previousItemSlug", n => { PreviousItemSlug = n.GetObjectValue<global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilterPreviousItemSlug>(global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilterPreviousItemSlug.CreateFromDiscriminatorValue); } },
                { "previousPageId", n => { PreviousPageId = n.GetObjectValue<global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilterPreviousPageId>(global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilterPreviousPageId.CreateFromDiscriminatorValue); } },
                { "referrer", n => { Referrer = n.GetObjectValue<global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilterReferrer>(global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilterReferrer.CreateFromDiscriminatorValue); } },
                { "region", n => { Region = n.GetObjectValue<global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilterRegion>(global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilterRegion.CreateFromDiscriminatorValue); } },
                { "timeOfDay", n => { TimeOfDay = n.GetObjectValue<global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilterTimeOfDay>(global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilterTimeOfDay.CreateFromDiscriminatorValue); } },
                { "timezone", n => { Timezone = n.GetObjectValue<global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilterTimezone>(global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilterTimezone.CreateFromDiscriminatorValue); } },
                { "trafficSource", n => { TrafficSource = n.GetObjectValue<global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilterTrafficSource>(global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilterTrafficSource.CreateFromDiscriminatorValue); } },
                { "utmCampaign", n => { UtmCampaign = n.GetObjectValue<global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilterUtmCampaign>(global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilterUtmCampaign.CreateFromDiscriminatorValue); } },
                { "utmContent", n => { UtmContent = n.GetObjectValue<global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilterUtmContent>(global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilterUtmContent.CreateFromDiscriminatorValue); } },
                { "utmMedium", n => { UtmMedium = n.GetObjectValue<global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilterUtmMedium>(global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilterUtmMedium.CreateFromDiscriminatorValue); } },
                { "utmSource", n => { UtmSource = n.GetObjectValue<global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilterUtmSource>(global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilterUtmSource.CreateFromDiscriminatorValue); } },
                { "utmTerm", n => { UtmTerm = n.GetObjectValue<global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilterUtmTerm>(global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilterUtmTerm.CreateFromDiscriminatorValue); } },
                { "visitStatus", n => { VisitStatus = n.GetObjectValue<global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilterVisitStatus>(global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilterVisitStatus.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilterAudienceIds>("audienceIds", AudienceIds);
            writer.WriteObjectValue<global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilterBrowser>("browser", Browser);
            writer.WriteObjectValue<global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilterCollectionId>("collectionId", CollectionId);
            writer.WriteObjectValue<global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilterCountry>("country", Country);
            writer.WriteObjectValue<global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilterDayOfWeek>("dayOfWeek", DayOfWeek);
            writer.WriteObjectValue<global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilterDeviceBrand>("deviceBrand", DeviceBrand);
            writer.WriteObjectValue<global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilterDeviceType>("deviceType", DeviceType);
            writer.WriteObjectValue<global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilterDomain>("domain", Domain);
            writer.WriteObjectValue<global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilterItemSlug>("itemSlug", ItemSlug);
            writer.WriteObjectValue<global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilterLanguage>("language", Language);
            writer.WriteObjectValue<global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilterLocale>("locale", Locale);
            writer.WriteObjectValue<global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilterNextCollectionId>("nextCollectionId", NextCollectionId);
            writer.WriteObjectValue<global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilterNextItemSlug>("nextItemSlug", NextItemSlug);
            writer.WriteObjectValue<global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilterNextPageId>("nextPageId", NextPageId);
            writer.WriteObjectValue<global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilterOs>("os", Os);
            writer.WriteObjectValue<global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilterPageId>("pageId", PageId);
            writer.WriteObjectValue<global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilterPagePath>("pagePath", PagePath);
            writer.WriteObjectValue<global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilterPreviousCollectionId>("previousCollectionId", PreviousCollectionId);
            writer.WriteObjectValue<global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilterPreviousItemSlug>("previousItemSlug", PreviousItemSlug);
            writer.WriteObjectValue<global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilterPreviousPageId>("previousPageId", PreviousPageId);
            writer.WriteObjectValue<global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilterReferrer>("referrer", Referrer);
            writer.WriteObjectValue<global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilterRegion>("region", Region);
            writer.WriteObjectValue<global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilterTimeOfDay>("timeOfDay", TimeOfDay);
            writer.WriteObjectValue<global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilterTimezone>("timezone", Timezone);
            writer.WriteObjectValue<global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilterTrafficSource>("trafficSource", TrafficSource);
            writer.WriteObjectValue<global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilterUtmCampaign>("utmCampaign", UtmCampaign);
            writer.WriteObjectValue<global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilterUtmContent>("utmContent", UtmContent);
            writer.WriteObjectValue<global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilterUtmMedium>("utmMedium", UtmMedium);
            writer.WriteObjectValue<global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilterUtmSource>("utmSource", UtmSource);
            writer.WriteObjectValue<global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilterUtmTerm>("utmTerm", UtmTerm);
            writer.WriteObjectValue<global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilterVisitStatus>("visitStatus", VisitStatus);
        }
    }
}
#pragma warning restore CS0618
