// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Webflow.OpenApiClient.Models
{
    /// <summary>
    /// Operators for filtering a single dimension. Specify at least one of `eq`, `in`, `ne`, or `nin`.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class GetAnalyzeTimeOnPageReport200ResponseFilterUtmSource : IParsable
    {
        /// <summary>Match values exactly equal to the provided value.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Eq { get; set; }
#nullable restore
#else
        public string Eq { get; set; }
#endif
        /// <summary>Match values in the provided list. Use indexed bracket notation — `filter[&lt;dimension&gt;][in][0]=value1&amp;filter[&lt;dimension&gt;][in][1]=value2`. Comma-separated values (for example, `filter[&lt;dimension&gt;][in]=value1,value2`) are not supported.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? In { get; set; }
#nullable restore
#else
        public List<string> In { get; set; }
#endif
        /// <summary>Exclude values exactly equal to the provided value.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Ne { get; set; }
#nullable restore
#else
        public string Ne { get; set; }
#endif
        /// <summary>Exclude values in the provided list. Use indexed bracket notation — `filter[&lt;dimension&gt;][nin][0]=value1&amp;filter[&lt;dimension&gt;][nin][1]=value2`. Comma-separated values (for example, `filter[&lt;dimension&gt;][nin]=value1,value2`) are not supported.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Nin { get; set; }
#nullable restore
#else
        public List<string> Nin { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTimeOnPageReport200ResponseFilterUtmSource"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTimeOnPageReport200ResponseFilterUtmSource CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTimeOnPageReport200ResponseFilterUtmSource();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "eq", n => { Eq = n.GetStringValue(); } },
                { "in", n => { In = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "ne", n => { Ne = n.GetStringValue(); } },
                { "nin", n => { Nin = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("eq", Eq);
            writer.WriteCollectionOfPrimitiveValues<string>("in", In);
            writer.WriteStringValue("ne", Ne);
            writer.WriteCollectionOfPrimitiveValues<string>("nin", Nin);
        }
    }
}
#pragma warning restore CS0618
