// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Webflow.OpenApiClient.Models
{
    /// <summary>
    /// A single event in the ranked response, with its event count over the requested window. Events are counted individually, not rolled up into sessions, users, or pageviews, so this report has no `metricScope` — `count` is always the number of times the event fired.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class GetAnalyzeTopEventsReport200ResponseDataItem : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>CMS collection-list rendering context for the event. Omitted when the event is not rendered inside a CMS collection list.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopEventsReport200ResponseDataItemCmsContextItem>? CmsContext { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopEventsReport200ResponseDataItemCmsContextItem> CmsContext { get; set; }
#endif
        /// <summary>Identifier of the CMS collection the associated page belongs to. Present only for events on CMS-templated pages.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CollectionId { get; set; }
#nullable restore
#else
        public string CollectionId { get; set; }
#endif
        /// <summary>Component rendering context for the event. Omitted when the event is not rendered inside a component.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopEventsReport200ResponseDataItemComponentContextItem>? ComponentContext { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopEventsReport200ResponseDataItemComponentContextItem> ComponentContext { get; set; }
#endif
        /// <summary>Number of times the event fired during the requested window.</summary>
        public int? Count { get; set; }
        /// <summary>Opaque identifier of the event.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EventId { get; set; }
#nullable restore
#else
        public string EventId { get; set; }
#endif
        /// <summary>Slug of the CMS item the associated page represents. Present only for events on CMS-templated pages.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ItemSlug { get; set; }
#nullable restore
#else
        public string ItemSlug { get; set; }
#endif
        /// <summary>Display name of the event. Omitted when the event has no name (customer-defined events may leave it blank).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>Identifier of the Webflow page the event is associated with. Omitted when the upstream has no page context for the event.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PageId { get; set; }
#nullable restore
#else
        public string PageId { get; set; }
#endif
        /// <summary>Display name of the associated page. Omitted when the page label is unknown.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PageName { get; set; }
#nullable restore
#else
        public string PageName { get; set; }
#endif
        /// <summary>Daily count timeseries for this event over the requested window. Returned when `timeseries` is requested.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopEventsReport200ResponseDataItemTimeseriesItem>? Timeseries { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopEventsReport200ResponseDataItemTimeseriesItem> Timeseries { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopEventsReport200ResponseDataItem"/> and sets the default values.
        /// </summary>
        public GetAnalyzeTopEventsReport200ResponseDataItem()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopEventsReport200ResponseDataItem"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopEventsReport200ResponseDataItem CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopEventsReport200ResponseDataItem();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "cmsContext", n => { CmsContext = n.GetCollectionOfObjectValues<global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopEventsReport200ResponseDataItemCmsContextItem>(global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopEventsReport200ResponseDataItemCmsContextItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "collectionId", n => { CollectionId = n.GetStringValue(); } },
                { "componentContext", n => { ComponentContext = n.GetCollectionOfObjectValues<global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopEventsReport200ResponseDataItemComponentContextItem>(global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopEventsReport200ResponseDataItemComponentContextItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "count", n => { Count = n.GetIntValue(); } },
                { "eventId", n => { EventId = n.GetStringValue(); } },
                { "itemSlug", n => { ItemSlug = n.GetStringValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "pageId", n => { PageId = n.GetStringValue(); } },
                { "pageName", n => { PageName = n.GetStringValue(); } },
                { "timeseries", n => { Timeseries = n.GetCollectionOfObjectValues<global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopEventsReport200ResponseDataItemTimeseriesItem>(global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopEventsReport200ResponseDataItemTimeseriesItem.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopEventsReport200ResponseDataItemCmsContextItem>("cmsContext", CmsContext);
            writer.WriteStringValue("collectionId", CollectionId);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopEventsReport200ResponseDataItemComponentContextItem>("componentContext", ComponentContext);
            writer.WriteIntValue("count", Count);
            writer.WriteStringValue("eventId", EventId);
            writer.WriteStringValue("itemSlug", ItemSlug);
            writer.WriteStringValue("name", Name);
            writer.WriteStringValue("pageId", PageId);
            writer.WriteStringValue("pageName", PageName);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopEventsReport200ResponseDataItemTimeseriesItem>("timeseries", Timeseries);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
