// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Webflow.OpenApiClient.Models
{
    /// <summary>
    /// Response payload for the top pages report.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class GetAnalyzeTopPagesReport200Response : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Daily bucketing applied to a response.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopPagesReport200ResponseBucketing? Bucketing { get; set; }
#nullable restore
#else
        public global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopPagesReport200ResponseBucketing Bucketing { get; set; }
#endif
        /// <summary>Pages ranked by `sortBy`, descending. At most `limit` rows.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopPagesReport200ResponseDataItem>? Data { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopPagesReport200ResponseDataItem> Data { get; set; }
#endif
        /// <summary>Filter the top pages report by dimension. Each property is an optional set of `AnalyzeFilterOperators` (`eq`, `in`, `ne`, `nin`) applied to the named dimension. Filter a given dimension in one place — either inside `filter` or as a top-level query parameter.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopPagesReport200ResponseFilter? Filter { get; set; }
#nullable restore
#else
        public global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopPagesReport200ResponseFilter Filter { get; set; }
#endif
        /// <summary>The row cap that was applied to this response (echoes the resolved request value, including the default).</summary>
        public int? Limit { get; set; }
        /// <summary>Discriminator identifying the report type.</summary>
        public global::Soenneker.Webflow.OpenApiClient.Models.TopPagesReport? Report { get; set; }
        /// <summary>The metric used to rank rows in the response, descending. Row-level `sessionCount`, `userCount`, and `pageviewCount` are always all returned regardless of `sortBy`.- `session`: rank by session count (default).- `user`: rank by unique user count.- `pageview`: rank by pageview count.</summary>
        public global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopPagesReport200ResponseSortBy? SortBy { get; set; }
        /// <summary>A reporting time window. `endTime` must be greater than `startTime`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopPagesReport200ResponseWindow? Window { get; set; }
#nullable restore
#else
        public global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopPagesReport200ResponseWindow Window { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopPagesReport200Response"/> and sets the default values.
        /// </summary>
        public GetAnalyzeTopPagesReport200Response()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopPagesReport200Response"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopPagesReport200Response CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopPagesReport200Response();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "bucketing", n => { Bucketing = n.GetObjectValue<global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopPagesReport200ResponseBucketing>(global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopPagesReport200ResponseBucketing.CreateFromDiscriminatorValue); } },
                { "data", n => { Data = n.GetCollectionOfObjectValues<global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopPagesReport200ResponseDataItem>(global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopPagesReport200ResponseDataItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "filter", n => { Filter = n.GetObjectValue<global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopPagesReport200ResponseFilter>(global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopPagesReport200ResponseFilter.CreateFromDiscriminatorValue); } },
                { "limit", n => { Limit = n.GetIntValue(); } },
                { "report", n => { Report = n.GetEnumValue<global::Soenneker.Webflow.OpenApiClient.Models.TopPagesReport>(); } },
                { "sortBy", n => { SortBy = n.GetEnumValue<global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopPagesReport200ResponseSortBy>(); } },
                { "window", n => { Window = n.GetObjectValue<global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopPagesReport200ResponseWindow>(global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopPagesReport200ResponseWindow.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopPagesReport200ResponseBucketing>("bucketing", Bucketing);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopPagesReport200ResponseDataItem>("data", Data);
            writer.WriteObjectValue<global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopPagesReport200ResponseFilter>("filter", Filter);
            writer.WriteIntValue("limit", Limit);
            writer.WriteEnumValue<global::Soenneker.Webflow.OpenApiClient.Models.TopPagesReport>("report", Report);
            writer.WriteEnumValue<global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopPagesReport200ResponseSortBy>("sortBy", SortBy);
            writer.WriteObjectValue<global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopPagesReport200ResponseWindow>("window", Window);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
