// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Webflow.OpenApiClient.Models
{
    /// <summary>
    /// Response payload for the top dimensions report.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class GetAnalyzeTopDimensionsReport200Response : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Dimension values ranked by `count`, descending. At most `limit` rows.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseDataItem>? Data { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseDataItem> Data { get; set; }
#endif
        /// <summary>The dimension whose top values are ranked.- `country`: ISO 3166-1 alpha-2 country code (e.g., `US`).- `region`: first-level subdivision below country, keyed by ISO 3166-2 code (e.g., `US-CA`, with `name` `California, United States`).- `deviceType`: `desktop`, `mobile`, or `tablet`.- `os`: operating system name (e.g., `iOS`, `Windows NT`).- `browser`: browser name (e.g., `Chrome`, `Safari`).- `language`: the visitor&apos;s stated language preference (from the `Accept-Language` request header).- `locale`: the locale declared on the visited page (the page&apos;s `&lt;html lang&gt;` value).- `referrer`: referrer domain (e.g., `google.com`).- `trafficSource`: traffic source category, keyed by a code: `DN` Direct, `SP` Paid Search, `SO` Organic Search, `CP` Paid Social, `CO` Organic Social, `EM` Email, `RC` Recirculation, `OP` Other Paid, `OT` Other, `AI` Generative AI. `attributeKey` is the code; `name` is the label.- `utmCampaign`: `utm_campaign` value.- `utmContent`: `utm_content` value.- `utmMedium`: `utm_medium` value.- `utmSource`: `utm_source` value.- `utmTerm`: `utm_term` value.- `audienceIds`: Webflow audience identifier. For this dimension, `attributeKey` is the audience ID and `name` is the audience&apos;s display name (falling back to the ID if no display name is set).</summary>
        public global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseDimension? Dimension { get; set; }
        /// <summary>Filter the top dimensions report by dimension. Each property is an optional set of `AnalyzeFilterOperators` (`eq`, `in`, `ne`, `nin`) applied to the named dimension. Filter a given dimension in one place — either inside `filter` or as a top-level query parameter.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilter? Filter { get; set; }
#nullable restore
#else
        public global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilter Filter { get; set; }
#endif
        /// <summary>The row cap that was applied to this response (echoes the resolved request value, including the default).</summary>
        public int? Limit { get; set; }
        /// <summary>The unit each row&apos;s `count` is measured in.- `session`: number of sessions attributed to the dimension value.- `user`: number of unique users attributed to the dimension value.</summary>
        public global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseMetricScope? MetricScope { get; set; }
        /// <summary>Discriminator identifying the report type.</summary>
        public global::Soenneker.Webflow.OpenApiClient.Models.TopDimensionsReport? Report { get; set; }
        /// <summary>A reporting time window. `endTime` must be greater than `startTime`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseWindow? Window { get; set; }
#nullable restore
#else
        public global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseWindow Window { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200Response"/> and sets the default values.
        /// </summary>
        public GetAnalyzeTopDimensionsReport200Response()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200Response"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200Response CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200Response();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "data", n => { Data = n.GetCollectionOfObjectValues<global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseDataItem>(global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseDataItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "dimension", n => { Dimension = n.GetEnumValue<global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseDimension>(); } },
                { "filter", n => { Filter = n.GetObjectValue<global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilter>(global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilter.CreateFromDiscriminatorValue); } },
                { "limit", n => { Limit = n.GetIntValue(); } },
                { "metricScope", n => { MetricScope = n.GetEnumValue<global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseMetricScope>(); } },
                { "report", n => { Report = n.GetEnumValue<global::Soenneker.Webflow.OpenApiClient.Models.TopDimensionsReport>(); } },
                { "window", n => { Window = n.GetObjectValue<global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseWindow>(global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseWindow.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseDataItem>("data", Data);
            writer.WriteEnumValue<global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseDimension>("dimension", Dimension);
            writer.WriteObjectValue<global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseFilter>("filter", Filter);
            writer.WriteIntValue("limit", Limit);
            writer.WriteEnumValue<global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseMetricScope>("metricScope", MetricScope);
            writer.WriteEnumValue<global::Soenneker.Webflow.OpenApiClient.Models.TopDimensionsReport>("report", Report);
            writer.WriteObjectValue<global::Soenneker.Webflow.OpenApiClient.Models.GetAnalyzeTopDimensionsReport200ResponseWindow>("window", Window);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
