// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Webflow.OpenApiClient.Models
{
    /// <summary>The type of the property.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum GetComponentContent200ResponseNodesItemComponentNodePropertyOverridesItemComponentPropertyTextType
    {
        [EnumMember(Value = "Plain Text")]
        #pragma warning disable CS1591
        PlainText,
        #pragma warning restore CS1591
        [EnumMember(Value = "Rich Text")]
        #pragma warning disable CS1591
        RichText,
        #pragma warning restore CS1591
        [EnumMember(Value = "Alt Text")]
        #pragma warning disable CS1591
        AltText,
        #pragma warning restore CS1591
    }
}
