// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Webflow.OpenApiClient.Models
{
    /// <summary>The type of the order address (billing or shipping)</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum GetOrder200ResponseShippingAddressType
    {
        [EnumMember(Value = "shipping")]
        #pragma warning disable CS1591
        Shipping,
        #pragma warning restore CS1591
        [EnumMember(Value = "billing")]
        #pragma warning disable CS1591
        Billing,
        #pragma warning restore CS1591
    }
}
