// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Webflow.OpenApiClient.Models
{
    /// <summary>
    /// Represents text content within the DOM. It contains both the raw text and its HTML representation. Additional attributes can be associated with the text for styling or other purposes.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class GetStaticContent200ResponseNodesItemTextNodeDom : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The custom attributes of the node</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Webflow.OpenApiClient.Models.GetStaticContent200ResponseNodesItemTextNodeDomAttributes? Attributes { get; set; }
#nullable restore
#else
        public global::Soenneker.Webflow.OpenApiClient.Models.GetStaticContent200ResponseNodesItemTextNodeDomAttributes Attributes { get; set; }
#endif
        /// <summary>Node UUID</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The text content of the node</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Webflow.OpenApiClient.Models.GetStaticContent200ResponseNodesItemTextNodeDomText? Text { get; set; }
#nullable restore
#else
        public global::Soenneker.Webflow.OpenApiClient.Models.GetStaticContent200ResponseNodesItemTextNodeDomText Text { get; set; }
#endif
        /// <summary>The type of the node</summary>
        public global::Soenneker.Webflow.OpenApiClient.Models.TextType? Type { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Webflow.OpenApiClient.Models.GetStaticContent200ResponseNodesItemTextNodeDom"/> and sets the default values.
        /// </summary>
        public GetStaticContent200ResponseNodesItemTextNodeDom()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Webflow.OpenApiClient.Models.GetStaticContent200ResponseNodesItemTextNodeDom"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Webflow.OpenApiClient.Models.GetStaticContent200ResponseNodesItemTextNodeDom CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Webflow.OpenApiClient.Models.GetStaticContent200ResponseNodesItemTextNodeDom();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "attributes", n => { Attributes = n.GetObjectValue<global::Soenneker.Webflow.OpenApiClient.Models.GetStaticContent200ResponseNodesItemTextNodeDomAttributes>(global::Soenneker.Webflow.OpenApiClient.Models.GetStaticContent200ResponseNodesItemTextNodeDomAttributes.CreateFromDiscriminatorValue); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "text", n => { Text = n.GetObjectValue<global::Soenneker.Webflow.OpenApiClient.Models.GetStaticContent200ResponseNodesItemTextNodeDomText>(global::Soenneker.Webflow.OpenApiClient.Models.GetStaticContent200ResponseNodesItemTextNodeDomText.CreateFromDiscriminatorValue); } },
                { "type", n => { Type = n.GetEnumValue<global::Soenneker.Webflow.OpenApiClient.Models.TextType>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Webflow.OpenApiClient.Models.GetStaticContent200ResponseNodesItemTextNodeDomAttributes>("attributes", Attributes);
            writer.WriteStringValue("id", Id);
            writer.WriteObjectValue<global::Soenneker.Webflow.OpenApiClient.Models.GetStaticContent200ResponseNodesItemTextNodeDomText>("text", Text);
            writer.WriteEnumValue<global::Soenneker.Webflow.OpenApiClient.Models.TextType>("type", Type);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
