// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Webflow.OpenApiClient.Models
{
    /// <summary>Name of the hosting plan.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum GetSitePlan200ResponseName
    {
        [EnumMember(Value = "Basic Hosting")]
        #pragma warning disable CS1591
        BasicHosting,
        #pragma warning restore CS1591
        [EnumMember(Value = "CMS Hosting")]
        #pragma warning disable CS1591
        CmsHosting,
        #pragma warning restore CS1591
        [EnumMember(Value = "Business Hosting")]
        #pragma warning disable CS1591
        BusinessHosting,
        #pragma warning restore CS1591
        [EnumMember(Value = "ECommerce Standard Hosting")]
        #pragma warning disable CS1591
        ECommerceStandardHosting,
        #pragma warning restore CS1591
        [EnumMember(Value = "ECommerce Plus Hosting")]
        #pragma warning disable CS1591
        ECommercePlusHosting,
        #pragma warning restore CS1591
        [EnumMember(Value = "ECommerce Advanced Hosting")]
        #pragma warning disable CS1591
        ECommerceAdvancedHosting,
        #pragma warning restore CS1591
    }
}
