// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Webflow.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetSiteActivityLogs200ResponseItemsItemEvent
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "styles_modified")]
        #pragma warning disable CS1591
        StylesModified,
        #pragma warning restore CS1591
        [EnumMember(Value = "site_published")]
        #pragma warning disable CS1591
        SitePublished,
        #pragma warning restore CS1591
        [EnumMember(Value = "ix2_modified_on_page")]
        #pragma warning disable CS1591
        Ix2ModifiedOnPage,
        #pragma warning restore CS1591
        [EnumMember(Value = "page_dom_modified")]
        #pragma warning disable CS1591
        PageDomModified,
        #pragma warning restore CS1591
        [EnumMember(Value = "cms_item")]
        #pragma warning disable CS1591
        CmsItem,
        #pragma warning restore CS1591
        [EnumMember(Value = "backup_created")]
        #pragma warning disable CS1591
        BackupCreated,
        #pragma warning restore CS1591
        [EnumMember(Value = "page_custom_code_modified")]
        #pragma warning disable CS1591
        PageCustomCodeModified,
        #pragma warning restore CS1591
        [EnumMember(Value = "symbols_modified")]
        #pragma warning disable CS1591
        SymbolsModified,
        #pragma warning restore CS1591
        [EnumMember(Value = "variable_modified")]
        #pragma warning disable CS1591
        VariableModified,
        #pragma warning restore CS1591
        [EnumMember(Value = "variables_modified")]
        #pragma warning disable CS1591
        VariablesModified,
        #pragma warning restore CS1591
        [EnumMember(Value = "cms_collection")]
        #pragma warning disable CS1591
        CmsCollection,
        #pragma warning restore CS1591
        [EnumMember(Value = "page_settings_modified")]
        #pragma warning disable CS1591
        PageSettingsModified,
        #pragma warning restore CS1591
        [EnumMember(Value = "page_settings_custom_code_modified")]
        #pragma warning disable CS1591
        PageSettingsCustomCodeModified,
        #pragma warning restore CS1591
        [EnumMember(Value = "ix2_modified_on_component")]
        #pragma warning disable CS1591
        Ix2ModifiedOnComponent,
        #pragma warning restore CS1591
        [EnumMember(Value = "ix2_modified_on_class")]
        #pragma warning disable CS1591
        Ix2ModifiedOnClass,
        #pragma warning restore CS1591
        [EnumMember(Value = "site_custom_code_modified")]
        #pragma warning disable CS1591
        SiteCustomCodeModified,
        #pragma warning restore CS1591
        [EnumMember(Value = "page_duplicated")]
        #pragma warning disable CS1591
        PageDuplicated,
        #pragma warning restore CS1591
        [EnumMember(Value = "secondary_locale_page_content_modified")]
        #pragma warning disable CS1591
        SecondaryLocalePageContentModified,
        #pragma warning restore CS1591
        [EnumMember(Value = "page_renamed")]
        #pragma warning disable CS1591
        PageRenamed,
        #pragma warning restore CS1591
        [EnumMember(Value = "page_created")]
        #pragma warning disable CS1591
        PageCreated,
        #pragma warning restore CS1591
        [EnumMember(Value = "page_deleted")]
        #pragma warning disable CS1591
        PageDeleted,
        #pragma warning restore CS1591
        [EnumMember(Value = "site_unpublished")]
        #pragma warning disable CS1591
        SiteUnpublished,
        #pragma warning restore CS1591
        [EnumMember(Value = "backup_restored")]
        #pragma warning disable CS1591
        BackupRestored,
        #pragma warning restore CS1591
        [EnumMember(Value = "locale_added")]
        #pragma warning disable CS1591
        LocaleAdded,
        #pragma warning restore CS1591
        [EnumMember(Value = "branch_created")]
        #pragma warning disable CS1591
        BranchCreated,
        #pragma warning restore CS1591
        [EnumMember(Value = "locale_display_name_updated")]
        #pragma warning disable CS1591
        LocaleDisplayNameUpdated,
        #pragma warning restore CS1591
        [EnumMember(Value = "locale_subdirectory_updated")]
        #pragma warning disable CS1591
        LocaleSubdirectoryUpdated,
        #pragma warning restore CS1591
        [EnumMember(Value = "branch_merged")]
        #pragma warning disable CS1591
        BranchMerged,
        #pragma warning restore CS1591
        [EnumMember(Value = "locale_tag_updated")]
        #pragma warning disable CS1591
        LocaleTagUpdated,
        #pragma warning restore CS1591
        [EnumMember(Value = "branch_deleted")]
        #pragma warning disable CS1591
        BranchDeleted,
        #pragma warning restore CS1591
        [EnumMember(Value = "locale_enabled")]
        #pragma warning disable CS1591
        LocaleEnabled,
        #pragma warning restore CS1591
        [EnumMember(Value = "locale_removed")]
        #pragma warning disable CS1591
        LocaleRemoved,
        #pragma warning restore CS1591
        [EnumMember(Value = "locale_disabled")]
        #pragma warning disable CS1591
        LocaleDisabled,
        #pragma warning restore CS1591
        [EnumMember(Value = "library_shared")]
        #pragma warning disable CS1591
        LibraryShared,
        #pragma warning restore CS1591
        [EnumMember(Value = "library_unshared")]
        #pragma warning disable CS1591
        LibraryUnshared,
        #pragma warning restore CS1591
        [EnumMember(Value = "library_installed")]
        #pragma warning disable CS1591
        LibraryInstalled,
        #pragma warning restore CS1591
        [EnumMember(Value = "library_uninstalled")]
        #pragma warning disable CS1591
        LibraryUninstalled,
        #pragma warning restore CS1591
        [EnumMember(Value = "library_update_shared")]
        #pragma warning disable CS1591
        LibraryUpdateShared,
        #pragma warning restore CS1591
        [EnumMember(Value = "library_update_accepted")]
        #pragma warning disable CS1591
        LibraryUpdateAccepted,
        #pragma warning restore CS1591
        [EnumMember(Value = "branch_review_created")]
        #pragma warning disable CS1591
        BranchReviewCreated,
        #pragma warning restore CS1591
        [EnumMember(Value = "branch_review_approved")]
        #pragma warning disable CS1591
        BranchReviewApproved,
        #pragma warning restore CS1591
        [EnumMember(Value = "branch_review_canceled")]
        #pragma warning disable CS1591
        BranchReviewCanceled,
        #pragma warning restore CS1591
    }
}
