// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Webflow.OpenApiClient.Models
{
    /// <summary>
    /// Represents a component instance within the DOM. It contains details about the component instance, such as its type and properties.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class GetStaticContent200ResponseNodesItemComponentNode : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The unique identifier of the component</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ComponentId { get; set; }
#nullable restore
#else
        public string ComponentId { get; set; }
#endif
        /// <summary>The unique identifier of the component instance node</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>List of component properties with overrides for a component instance.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Webflow.OpenApiClient.Models.GetStaticContent200ResponseNodesItemComponentNodePropertyOverridesItem>? PropertyOverrides { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Webflow.OpenApiClient.Models.GetStaticContent200ResponseNodesItemComponentNodePropertyOverridesItem> PropertyOverrides { get; set; }
#endif
        /// <summary>The type of the node</summary>
        public global::Soenneker.Webflow.OpenApiClient.Models.ComponentInstanceType? Type { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Webflow.OpenApiClient.Models.GetStaticContent200ResponseNodesItemComponentNode"/> and sets the default values.
        /// </summary>
        public GetStaticContent200ResponseNodesItemComponentNode()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Webflow.OpenApiClient.Models.GetStaticContent200ResponseNodesItemComponentNode"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Webflow.OpenApiClient.Models.GetStaticContent200ResponseNodesItemComponentNode CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Webflow.OpenApiClient.Models.GetStaticContent200ResponseNodesItemComponentNode();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "componentId", n => { ComponentId = n.GetStringValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "propertyOverrides", n => { PropertyOverrides = n.GetCollectionOfObjectValues<global::Soenneker.Webflow.OpenApiClient.Models.GetStaticContent200ResponseNodesItemComponentNodePropertyOverridesItem>(global::Soenneker.Webflow.OpenApiClient.Models.GetStaticContent200ResponseNodesItemComponentNodePropertyOverridesItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "type", n => { Type = n.GetEnumValue<global::Soenneker.Webflow.OpenApiClient.Models.ComponentInstanceType>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("componentId", ComponentId);
            writer.WriteStringValue("id", Id);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Webflow.OpenApiClient.Models.GetStaticContent200ResponseNodesItemComponentNodePropertyOverridesItem>("propertyOverrides", PropertyOverrides);
            writer.WriteEnumValue<global::Soenneker.Webflow.OpenApiClient.Models.ComponentInstanceType>("type", Type);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
