// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Webflow.OpenApiClient.Models
{
    /// <summary>The system that originated the event. `WEBFLOW_AI` for Webflow AI features, `WEBFLOW_MCP` for an external MCP server or Bridge App, `DESIGNER` for human writes from the Designer, and `SYSTEM` for automated Webflow processes such as backups or migrations. `null` for legacy events recorded before attribution was available.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum GetSiteActivityLogs200ResponseItemsItemSource
    {
        [EnumMember(Value = "WEBFLOW_AI")]
        #pragma warning disable CS1591
        WebflowAi,
        #pragma warning restore CS1591
        [EnumMember(Value = "WEBFLOW_MCP")]
        #pragma warning disable CS1591
        WebflowMcp,
        #pragma warning restore CS1591
        [EnumMember(Value = "DESIGNER")]
        #pragma warning disable CS1591
        Designer,
        #pragma warning restore CS1591
        [EnumMember(Value = "SYSTEM")]
        #pragma warning disable CS1591
        System,
        #pragma warning restore CS1591
    }
}
