// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Webflow.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.Webflow.OpenApiClient.Models.GetStaticContent200ResponseNodesItemComponentNode"/>, <see cref="global::Soenneker.Webflow.OpenApiClient.Models.GetStaticContent200ResponseNodesItemImageNode"/>, <see cref="global::Soenneker.Webflow.OpenApiClient.Models.GetStaticContent200ResponseNodesItemSearchButtonNode"/>, <see cref="global::Soenneker.Webflow.OpenApiClient.Models.GetStaticContent200ResponseNodesItemSelectNode"/>, <see cref="global::Soenneker.Webflow.OpenApiClient.Models.GetStaticContent200ResponseNodesItemSubmitButtonNode"/>, <see cref="global::Soenneker.Webflow.OpenApiClient.Models.GetStaticContent200ResponseNodesItemTextInputNode"/>, <see cref="global::Soenneker.Webflow.OpenApiClient.Models.GetStaticContent200ResponseNodesItemTextNodeDom"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class GetStaticContent200ResponseNodesItem : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Webflow.OpenApiClient.Models.GetStaticContent200ResponseNodesItemComponentNode"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Webflow.OpenApiClient.Models.GetStaticContent200ResponseNodesItemComponentNode? GetStaticContent200ResponseNodesItemComponentNode { get; set; }
#nullable restore
#else
        public global::Soenneker.Webflow.OpenApiClient.Models.GetStaticContent200ResponseNodesItemComponentNode GetStaticContent200ResponseNodesItemComponentNode { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Webflow.OpenApiClient.Models.GetStaticContent200ResponseNodesItemImageNode"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Webflow.OpenApiClient.Models.GetStaticContent200ResponseNodesItemImageNode? GetStaticContent200ResponseNodesItemImageNode { get; set; }
#nullable restore
#else
        public global::Soenneker.Webflow.OpenApiClient.Models.GetStaticContent200ResponseNodesItemImageNode GetStaticContent200ResponseNodesItemImageNode { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Webflow.OpenApiClient.Models.GetStaticContent200ResponseNodesItemSearchButtonNode"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Webflow.OpenApiClient.Models.GetStaticContent200ResponseNodesItemSearchButtonNode? GetStaticContent200ResponseNodesItemSearchButtonNode { get; set; }
#nullable restore
#else
        public global::Soenneker.Webflow.OpenApiClient.Models.GetStaticContent200ResponseNodesItemSearchButtonNode GetStaticContent200ResponseNodesItemSearchButtonNode { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Webflow.OpenApiClient.Models.GetStaticContent200ResponseNodesItemSelectNode"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Webflow.OpenApiClient.Models.GetStaticContent200ResponseNodesItemSelectNode? GetStaticContent200ResponseNodesItemSelectNode { get; set; }
#nullable restore
#else
        public global::Soenneker.Webflow.OpenApiClient.Models.GetStaticContent200ResponseNodesItemSelectNode GetStaticContent200ResponseNodesItemSelectNode { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Webflow.OpenApiClient.Models.GetStaticContent200ResponseNodesItemSubmitButtonNode"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Webflow.OpenApiClient.Models.GetStaticContent200ResponseNodesItemSubmitButtonNode? GetStaticContent200ResponseNodesItemSubmitButtonNode { get; set; }
#nullable restore
#else
        public global::Soenneker.Webflow.OpenApiClient.Models.GetStaticContent200ResponseNodesItemSubmitButtonNode GetStaticContent200ResponseNodesItemSubmitButtonNode { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Webflow.OpenApiClient.Models.GetStaticContent200ResponseNodesItemTextInputNode"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Webflow.OpenApiClient.Models.GetStaticContent200ResponseNodesItemTextInputNode? GetStaticContent200ResponseNodesItemTextInputNode { get; set; }
#nullable restore
#else
        public global::Soenneker.Webflow.OpenApiClient.Models.GetStaticContent200ResponseNodesItemTextInputNode GetStaticContent200ResponseNodesItemTextInputNode { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Webflow.OpenApiClient.Models.GetStaticContent200ResponseNodesItemTextNodeDom"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Webflow.OpenApiClient.Models.GetStaticContent200ResponseNodesItemTextNodeDom? GetStaticContent200ResponseNodesItemTextNodeDom { get; set; }
#nullable restore
#else
        public global::Soenneker.Webflow.OpenApiClient.Models.GetStaticContent200ResponseNodesItemTextNodeDom GetStaticContent200ResponseNodesItemTextNodeDom { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Webflow.OpenApiClient.Models.GetStaticContent200ResponseNodesItem"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Webflow.OpenApiClient.Models.GetStaticContent200ResponseNodesItem CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
            var result = new global::Soenneker.Webflow.OpenApiClient.Models.GetStaticContent200ResponseNodesItem();
            if("GetStaticContent200ResponseNodesItemComponentNode".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.GetStaticContent200ResponseNodesItemComponentNode = new global::Soenneker.Webflow.OpenApiClient.Models.GetStaticContent200ResponseNodesItemComponentNode();
            }
            else if("GetStaticContent200ResponseNodesItemImageNode".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.GetStaticContent200ResponseNodesItemImageNode = new global::Soenneker.Webflow.OpenApiClient.Models.GetStaticContent200ResponseNodesItemImageNode();
            }
            else if("GetStaticContent200ResponseNodesItemSearchButtonNode".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.GetStaticContent200ResponseNodesItemSearchButtonNode = new global::Soenneker.Webflow.OpenApiClient.Models.GetStaticContent200ResponseNodesItemSearchButtonNode();
            }
            else if("GetStaticContent200ResponseNodesItemSelectNode".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.GetStaticContent200ResponseNodesItemSelectNode = new global::Soenneker.Webflow.OpenApiClient.Models.GetStaticContent200ResponseNodesItemSelectNode();
            }
            else if("GetStaticContent200ResponseNodesItemSubmitButtonNode".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.GetStaticContent200ResponseNodesItemSubmitButtonNode = new global::Soenneker.Webflow.OpenApiClient.Models.GetStaticContent200ResponseNodesItemSubmitButtonNode();
            }
            else if("GetStaticContent200ResponseNodesItemTextInputNode".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.GetStaticContent200ResponseNodesItemTextInputNode = new global::Soenneker.Webflow.OpenApiClient.Models.GetStaticContent200ResponseNodesItemTextInputNode();
            }
            else if("GetStaticContent200ResponseNodesItemTextNodeDom".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.GetStaticContent200ResponseNodesItemTextNodeDom = new global::Soenneker.Webflow.OpenApiClient.Models.GetStaticContent200ResponseNodesItemTextNodeDom();
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(GetStaticContent200ResponseNodesItemComponentNode != null)
            {
                return GetStaticContent200ResponseNodesItemComponentNode.GetFieldDeserializers();
            }
            else if(GetStaticContent200ResponseNodesItemImageNode != null)
            {
                return GetStaticContent200ResponseNodesItemImageNode.GetFieldDeserializers();
            }
            else if(GetStaticContent200ResponseNodesItemSearchButtonNode != null)
            {
                return GetStaticContent200ResponseNodesItemSearchButtonNode.GetFieldDeserializers();
            }
            else if(GetStaticContent200ResponseNodesItemSelectNode != null)
            {
                return GetStaticContent200ResponseNodesItemSelectNode.GetFieldDeserializers();
            }
            else if(GetStaticContent200ResponseNodesItemSubmitButtonNode != null)
            {
                return GetStaticContent200ResponseNodesItemSubmitButtonNode.GetFieldDeserializers();
            }
            else if(GetStaticContent200ResponseNodesItemTextInputNode != null)
            {
                return GetStaticContent200ResponseNodesItemTextInputNode.GetFieldDeserializers();
            }
            else if(GetStaticContent200ResponseNodesItemTextNodeDom != null)
            {
                return GetStaticContent200ResponseNodesItemTextNodeDom.GetFieldDeserializers();
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(GetStaticContent200ResponseNodesItemComponentNode != null)
            {
                writer.WriteObjectValue<global::Soenneker.Webflow.OpenApiClient.Models.GetStaticContent200ResponseNodesItemComponentNode>(null, GetStaticContent200ResponseNodesItemComponentNode);
            }
            else if(GetStaticContent200ResponseNodesItemImageNode != null)
            {
                writer.WriteObjectValue<global::Soenneker.Webflow.OpenApiClient.Models.GetStaticContent200ResponseNodesItemImageNode>(null, GetStaticContent200ResponseNodesItemImageNode);
            }
            else if(GetStaticContent200ResponseNodesItemSearchButtonNode != null)
            {
                writer.WriteObjectValue<global::Soenneker.Webflow.OpenApiClient.Models.GetStaticContent200ResponseNodesItemSearchButtonNode>(null, GetStaticContent200ResponseNodesItemSearchButtonNode);
            }
            else if(GetStaticContent200ResponseNodesItemSelectNode != null)
            {
                writer.WriteObjectValue<global::Soenneker.Webflow.OpenApiClient.Models.GetStaticContent200ResponseNodesItemSelectNode>(null, GetStaticContent200ResponseNodesItemSelectNode);
            }
            else if(GetStaticContent200ResponseNodesItemSubmitButtonNode != null)
            {
                writer.WriteObjectValue<global::Soenneker.Webflow.OpenApiClient.Models.GetStaticContent200ResponseNodesItemSubmitButtonNode>(null, GetStaticContent200ResponseNodesItemSubmitButtonNode);
            }
            else if(GetStaticContent200ResponseNodesItemTextInputNode != null)
            {
                writer.WriteObjectValue<global::Soenneker.Webflow.OpenApiClient.Models.GetStaticContent200ResponseNodesItemTextInputNode>(null, GetStaticContent200ResponseNodesItemTextInputNode);
            }
            else if(GetStaticContent200ResponseNodesItemTextNodeDom != null)
            {
                writer.WriteObjectValue<global::Soenneker.Webflow.OpenApiClient.Models.GetStaticContent200ResponseNodesItemTextNodeDom>(null, GetStaticContent200ResponseNodesItemTextNodeDom);
            }
        }
    }
}
#pragma warning restore CS0618
