// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Webflow.OpenApiClient.Models
{
    /// <summary>Whether the Custom Code script is applied at the Site-level or Page-level</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum GetSiteCustomCodeBlocks200ResponseBlocksItemType
    {
        [EnumMember(Value = "page")]
        #pragma warning disable CS1591
        Page,
        #pragma warning restore CS1591
        [EnumMember(Value = "site")]
        #pragma warning disable CS1591
        Site,
        #pragma warning restore CS1591
    }
}
