// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Webflow.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetWorkspaceAuditLogs200ResponseItemsItemWorkspaceInvitationEventSubType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "invite_sent")]
        #pragma warning disable CS1591
        InviteSent,
        #pragma warning restore CS1591
        [EnumMember(Value = "invite_accepted")]
        #pragma warning disable CS1591
        InviteAccepted,
        #pragma warning restore CS1591
        [EnumMember(Value = "invite_updated")]
        #pragma warning disable CS1591
        InviteUpdated,
        #pragma warning restore CS1591
        [EnumMember(Value = "invite_canceled")]
        #pragma warning disable CS1591
        InviteCanceled,
        #pragma warning restore CS1591
        [EnumMember(Value = "invite_declined")]
        #pragma warning disable CS1591
        InviteDeclined,
        #pragma warning restore CS1591
        [EnumMember(Value = "access_request_accepted")]
        #pragma warning disable CS1591
        AccessRequestAccepted,
        #pragma warning restore CS1591
    }
}
