// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Webflow.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetWorkspaceAuditLogs200ResponseItemsItemWorkspaceMembershipEventSubType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "user_added")]
        #pragma warning disable CS1591
        UserAdded,
        #pragma warning restore CS1591
        [EnumMember(Value = "user_removed")]
        #pragma warning disable CS1591
        UserRemoved,
        #pragma warning restore CS1591
        [EnumMember(Value = "user_role_updated")]
        #pragma warning disable CS1591
        UserRoleUpdated,
        #pragma warning restore CS1591
    }
}
