// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Webflow.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetWorkspaceAuditLogs200ResponseItemsItemWorkspaceInvitationPayloadUserType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "member")]
        #pragma warning disable CS1591
        Member,
        #pragma warning restore CS1591
        [EnumMember(Value = "guest")]
        #pragma warning disable CS1591
        Guest,
        #pragma warning restore CS1591
        [EnumMember(Value = "reviewer")]
        #pragma warning disable CS1591
        Reviewer,
        #pragma warning restore CS1591
        [EnumMember(Value = "client")]
        #pragma warning disable CS1591
        Client,
        #pragma warning restore CS1591
    }
}
