// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Webflow.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetWorkspaceAuditLogs200ResponseItemsItemCustomRoleEventSubType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "role_created")]
        #pragma warning disable CS1591
        RoleCreated,
        #pragma warning restore CS1591
        [EnumMember(Value = "role_updated")]
        #pragma warning disable CS1591
        RoleUpdated,
        #pragma warning restore CS1591
        [EnumMember(Value = "role_deleted")]
        #pragma warning disable CS1591
        RoleDeleted,
        #pragma warning restore CS1591
    }
}
