// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Webflow.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetWorkspaceAuditLogs200ResponseItemsItemSettingChangePayloadMethod
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "dashboard")]
        #pragma warning disable CS1591
        Dashboard,
        #pragma warning restore CS1591
        [EnumMember(Value = "admin")]
        #pragma warning disable CS1591
        Admin,
        #pragma warning restore CS1591
    }
}
