// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Webflow.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ListWebhooks200Response : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Pagination object</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Webflow.OpenApiClient.Models.ListWebhooks200ResponsePagination? Pagination { get; set; }
#nullable restore
#else
        public global::Soenneker.Webflow.OpenApiClient.Models.ListWebhooks200ResponsePagination Pagination { get; set; }
#endif
        /// <summary>The webhooks property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Webflow.OpenApiClient.Models.ListWebhooks200ResponseWebhooksItem>? Webhooks { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Webflow.OpenApiClient.Models.ListWebhooks200ResponseWebhooksItem> Webhooks { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Webflow.OpenApiClient.Models.ListWebhooks200Response"/> and sets the default values.
        /// </summary>
        public ListWebhooks200Response()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Webflow.OpenApiClient.Models.ListWebhooks200Response"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Webflow.OpenApiClient.Models.ListWebhooks200Response CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Webflow.OpenApiClient.Models.ListWebhooks200Response();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "pagination", n => { Pagination = n.GetObjectValue<global::Soenneker.Webflow.OpenApiClient.Models.ListWebhooks200ResponsePagination>(global::Soenneker.Webflow.OpenApiClient.Models.ListWebhooks200ResponsePagination.CreateFromDiscriminatorValue); } },
                { "webhooks", n => { Webhooks = n.GetCollectionOfObjectValues<global::Soenneker.Webflow.OpenApiClient.Models.ListWebhooks200ResponseWebhooksItem>(global::Soenneker.Webflow.OpenApiClient.Models.ListWebhooks200ResponseWebhooksItem.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Webflow.OpenApiClient.Models.ListWebhooks200ResponsePagination>("pagination", Pagination);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Webflow.OpenApiClient.Models.ListWebhooks200ResponseWebhooksItem>("webhooks", Webhooks);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
