// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Webflow.OpenApiClient.Models
{
    /// <summary>
    /// An object with various Stripe IDs, useful for linking into the stripe dashboard.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ListOrders200ResponseOrdersItemStripeDetails : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Stripe-generated charge identifier, or null</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ChargeId { get; set; }
#nullable restore
#else
        public string ChargeId { get; set; }
#endif
        /// <summary>Stripe-generated customer identifier, or null</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CustomerId { get; set; }
#nullable restore
#else
        public string CustomerId { get; set; }
#endif
        /// <summary>Stripe-generated dispute identifier, or null</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DisputeId { get; set; }
#nullable restore
#else
        public string DisputeId { get; set; }
#endif
        /// <summary>Stripe-generated identifier for the PaymentIntent, or null</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PaymentIntentId { get; set; }
#nullable restore
#else
        public string PaymentIntentId { get; set; }
#endif
        /// <summary>Stripe-generated identifier for the PaymentMethod used</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PaymentMethod { get; set; }
#nullable restore
#else
        public string PaymentMethod { get; set; }
#endif
        /// <summary>Stripe-generated refund identifier, or null</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RefundId { get; set; }
#nullable restore
#else
        public string RefundId { get; set; }
#endif
        /// <summary>Stripe-generated refund reason, or null</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RefundReason { get; set; }
#nullable restore
#else
        public string RefundReason { get; set; }
#endif
        /// <summary>Stripe-generated identifier for the Subscription</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SubscriptionId { get; set; }
#nullable restore
#else
        public string SubscriptionId { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Webflow.OpenApiClient.Models.ListOrders200ResponseOrdersItemStripeDetails"/> and sets the default values.
        /// </summary>
        public ListOrders200ResponseOrdersItemStripeDetails()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Webflow.OpenApiClient.Models.ListOrders200ResponseOrdersItemStripeDetails"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Webflow.OpenApiClient.Models.ListOrders200ResponseOrdersItemStripeDetails CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Webflow.OpenApiClient.Models.ListOrders200ResponseOrdersItemStripeDetails();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "chargeId", n => { ChargeId = n.GetStringValue(); } },
                { "customerId", n => { CustomerId = n.GetStringValue(); } },
                { "disputeId", n => { DisputeId = n.GetStringValue(); } },
                { "paymentIntentId", n => { PaymentIntentId = n.GetStringValue(); } },
                { "paymentMethod", n => { PaymentMethod = n.GetStringValue(); } },
                { "refundId", n => { RefundId = n.GetStringValue(); } },
                { "refundReason", n => { RefundReason = n.GetStringValue(); } },
                { "subscriptionId", n => { SubscriptionId = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("chargeId", ChargeId);
            writer.WriteStringValue("customerId", CustomerId);
            writer.WriteStringValue("disputeId", DisputeId);
            writer.WriteStringValue("paymentIntentId", PaymentIntentId);
            writer.WriteStringValue("paymentMethod", PaymentMethod);
            writer.WriteStringValue("refundId", RefundId);
            writer.WriteStringValue("refundReason", RefundReason);
            writer.WriteStringValue("subscriptionId", SubscriptionId);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
