// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Webflow.OpenApiClient.Models
{
    /// <summary>Product tax class</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ListProducts200ResponseItemsItemProductFieldDataTaxCategory
    {
        [EnumMember(Value = "standard-taxable")]
        #pragma warning disable CS1591
        StandardTaxable,
        #pragma warning restore CS1591
        [EnumMember(Value = "standard-exempt")]
        #pragma warning disable CS1591
        StandardExempt,
        #pragma warning restore CS1591
        [EnumMember(Value = "books-religious")]
        #pragma warning disable CS1591
        BooksReligious,
        #pragma warning restore CS1591
        [EnumMember(Value = "books-textbook")]
        #pragma warning disable CS1591
        BooksTextbook,
        #pragma warning restore CS1591
        [EnumMember(Value = "clothing")]
        #pragma warning disable CS1591
        Clothing,
        #pragma warning restore CS1591
        [EnumMember(Value = "clothing-swimwear")]
        #pragma warning disable CS1591
        ClothingSwimwear,
        #pragma warning restore CS1591
        [EnumMember(Value = "digital-goods")]
        #pragma warning disable CS1591
        DigitalGoods,
        #pragma warning restore CS1591
        [EnumMember(Value = "digital-service")]
        #pragma warning disable CS1591
        DigitalService,
        #pragma warning restore CS1591
        [EnumMember(Value = "drugs-non-prescription")]
        #pragma warning disable CS1591
        DrugsNonPrescription,
        #pragma warning restore CS1591
        [EnumMember(Value = "drugs-prescription")]
        #pragma warning disable CS1591
        DrugsPrescription,
        #pragma warning restore CS1591
        [EnumMember(Value = "food-bottled-water")]
        #pragma warning disable CS1591
        FoodBottledWater,
        #pragma warning restore CS1591
        [EnumMember(Value = "food-candy")]
        #pragma warning disable CS1591
        FoodCandy,
        #pragma warning restore CS1591
        [EnumMember(Value = "food-groceries")]
        #pragma warning disable CS1591
        FoodGroceries,
        #pragma warning restore CS1591
        [EnumMember(Value = "food-prepared")]
        #pragma warning disable CS1591
        FoodPrepared,
        #pragma warning restore CS1591
        [EnumMember(Value = "food-soda")]
        #pragma warning disable CS1591
        FoodSoda,
        #pragma warning restore CS1591
        [EnumMember(Value = "food-supplements")]
        #pragma warning disable CS1591
        FoodSupplements,
        #pragma warning restore CS1591
        [EnumMember(Value = "magazine-individual")]
        #pragma warning disable CS1591
        MagazineIndividual,
        #pragma warning restore CS1591
        [EnumMember(Value = "magazine-subscription")]
        #pragma warning disable CS1591
        MagazineSubscription,
        #pragma warning restore CS1591
        [EnumMember(Value = "service-admission")]
        #pragma warning disable CS1591
        ServiceAdmission,
        #pragma warning restore CS1591
        [EnumMember(Value = "service-advertising")]
        #pragma warning disable CS1591
        ServiceAdvertising,
        #pragma warning restore CS1591
        [EnumMember(Value = "service-dry-cleaning")]
        #pragma warning disable CS1591
        ServiceDryCleaning,
        #pragma warning restore CS1591
        [EnumMember(Value = "service-hairdressing")]
        #pragma warning disable CS1591
        ServiceHairdressing,
        #pragma warning restore CS1591
        [EnumMember(Value = "service-installation")]
        #pragma warning disable CS1591
        ServiceInstallation,
        #pragma warning restore CS1591
        [EnumMember(Value = "service-miscellaneous")]
        #pragma warning disable CS1591
        ServiceMiscellaneous,
        #pragma warning restore CS1591
        [EnumMember(Value = "service-parking")]
        #pragma warning disable CS1591
        ServiceParking,
        #pragma warning restore CS1591
        [EnumMember(Value = "service-printing")]
        #pragma warning disable CS1591
        ServicePrinting,
        #pragma warning restore CS1591
        [EnumMember(Value = "service-professional")]
        #pragma warning disable CS1591
        ServiceProfessional,
        #pragma warning restore CS1591
        [EnumMember(Value = "service-repair")]
        #pragma warning disable CS1591
        ServiceRepair,
        #pragma warning restore CS1591
        [EnumMember(Value = "service-training")]
        #pragma warning disable CS1591
        ServiceTraining,
        #pragma warning restore CS1591
    }
}
