// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Webflow.OpenApiClient.Models
{
    /// <summary>
    /// The payload of data sent from Webflow
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PageDeletedRequestPayload : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Whether the page is archived</summary>
        public bool? Archived { get; set; }
        /// <summary>The deletedOn property</summary>
        public DateTimeOffset? DeletedOn { get; set; }
        /// <summary>Whether the page is a draft</summary>
        public bool? Draft { get; set; }
        /// <summary>Whether the page belongs to a branch</summary>
        public bool? IsBranch { get; set; }
        /// <summary>The pageId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PageId { get; set; }
#nullable restore
#else
        public string PageId { get; set; }
#endif
        /// <summary>The display name of the page, or null if not set</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PageName { get; set; }
#nullable restore
#else
        public string PageName { get; set; }
#endif
        /// <summary>The pageTitle property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PageTitle { get; set; }
#nullable restore
#else
        public string PageTitle { get; set; }
#endif
        /// <summary>The publishedPath property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PublishedPath { get; set; }
#nullable restore
#else
        public string PublishedPath { get; set; }
#endif
        /// <summary>The siteId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SiteId { get; set; }
#nullable restore
#else
        public string SiteId { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Webflow.OpenApiClient.Models.PageDeletedRequestPayload"/> and sets the default values.
        /// </summary>
        public PageDeletedRequestPayload()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Webflow.OpenApiClient.Models.PageDeletedRequestPayload"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Webflow.OpenApiClient.Models.PageDeletedRequestPayload CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Webflow.OpenApiClient.Models.PageDeletedRequestPayload();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "archived", n => { Archived = n.GetBoolValue(); } },
                { "deletedOn", n => { DeletedOn = n.GetDateTimeOffsetValue(); } },
                { "draft", n => { Draft = n.GetBoolValue(); } },
                { "isBranch", n => { IsBranch = n.GetBoolValue(); } },
                { "pageId", n => { PageId = n.GetStringValue(); } },
                { "pageName", n => { PageName = n.GetStringValue(); } },
                { "pageTitle", n => { PageTitle = n.GetStringValue(); } },
                { "publishedPath", n => { PublishedPath = n.GetStringValue(); } },
                { "siteId", n => { SiteId = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("archived", Archived);
            writer.WriteDateTimeOffsetValue("deletedOn", DeletedOn);
            writer.WriteBoolValue("draft", Draft);
            writer.WriteBoolValue("isBranch", IsBranch);
            writer.WriteStringValue("pageId", PageId);
            writer.WriteStringValue("pageName", PageName);
            writer.WriteStringValue("pageTitle", PageTitle);
            writer.WriteStringValue("publishedPath", PublishedPath);
            writer.WriteStringValue("siteId", SiteId);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
