// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Webflow.OpenApiClient.Models
{
    /// <summary>The content type of the file. Defaults to application/json</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum SetWellKnownRequestContentType
    {
        [EnumMember(Value = "application/json")]
        #pragma warning disable CS1591
        ApplicationJson,
        #pragma warning restore CS1591
        [EnumMember(Value = "text/plain")]
        #pragma warning disable CS1591
        TextPlain,
        #pragma warning restore CS1591
    }
}
