// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Webflow.OpenApiClient.Models
{
    /// <summary>
    /// The payload of data sent from Webflow
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SitePublish2RequestPayload : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The domains that were published</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Domains { get; set; }
#nullable restore
#else
        public List<string> Domains { get; set; }
#endif
        /// <summary>The ID of the page that was published</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PageId { get; set; }
#nullable restore
#else
        public string PageId { get; set; }
#endif
        /// <summary>The name and ID of the user who published the site</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Webflow.OpenApiClient.Models.SitePublish2RequestPayloadPublishedBy? PublishedBy { get; set; }
#nullable restore
#else
        public global::Soenneker.Webflow.OpenApiClient.Models.SitePublish2RequestPayloadPublishedBy PublishedBy { get; set; }
#endif
        /// <summary>The timestamp of the publish event</summary>
        public DateTimeOffset? PublishedOn { get; set; }
        /// <summary>Whether the entire site or an individual page was published</summary>
        public global::Soenneker.Webflow.OpenApiClient.Models.SitePublish2RequestPayloadPublishScope? PublishScope { get; set; }
        /// <summary>The ID of the site that was published</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SiteId { get; set; }
#nullable restore
#else
        public string SiteId { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Webflow.OpenApiClient.Models.SitePublish2RequestPayload"/> and sets the default values.
        /// </summary>
        public SitePublish2RequestPayload()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Webflow.OpenApiClient.Models.SitePublish2RequestPayload"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Webflow.OpenApiClient.Models.SitePublish2RequestPayload CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Webflow.OpenApiClient.Models.SitePublish2RequestPayload();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "domains", n => { Domains = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "pageId", n => { PageId = n.GetStringValue(); } },
                { "publishScope", n => { PublishScope = n.GetEnumValue<global::Soenneker.Webflow.OpenApiClient.Models.SitePublish2RequestPayloadPublishScope>(); } },
                { "publishedBy", n => { PublishedBy = n.GetObjectValue<global::Soenneker.Webflow.OpenApiClient.Models.SitePublish2RequestPayloadPublishedBy>(global::Soenneker.Webflow.OpenApiClient.Models.SitePublish2RequestPayloadPublishedBy.CreateFromDiscriminatorValue); } },
                { "publishedOn", n => { PublishedOn = n.GetDateTimeOffsetValue(); } },
                { "siteId", n => { SiteId = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfPrimitiveValues<string>("domains", Domains);
            writer.WriteStringValue("pageId", PageId);
            writer.WriteObjectValue<global::Soenneker.Webflow.OpenApiClient.Models.SitePublish2RequestPayloadPublishedBy>("publishedBy", PublishedBy);
            writer.WriteDateTimeOffsetValue("publishedOn", PublishedOn);
            writer.WriteEnumValue<global::Soenneker.Webflow.OpenApiClient.Models.SitePublish2RequestPayloadPublishScope>("publishScope", PublishScope);
            writer.WriteStringValue("siteId", SiteId);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
