// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Webflow.OpenApiClient.Models
{
    /// <summary>The platform of the subscription plan</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum StripePlatform
    {
        [EnumMember(Value = "stripe")]
        #pragma warning disable CS1591
        Stripe,
        #pragma warning restore CS1591
    }
}
