// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Webflow.OpenApiClient.Models
{
    /// <summary>Discriminator identifying the report type.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum TrafficReport
    {
        [EnumMember(Value = "traffic")]
        #pragma warning disable CS1591
        Traffic,
        #pragma warning restore CS1591
    }
}
