// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Webflow.OpenApiClient.Models
{
    /// <summary>
    /// A customer address
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class UnfulfillOrder200ResponseAllAddressesItem : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Display name on the address</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Addressee { get; set; }
#nullable restore
#else
        public string Addressee { get; set; }
#endif
        /// <summary>The city of the address.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? City { get; set; }
#nullable restore
#else
        public string City { get; set; }
#endif
        /// <summary>The country of the address</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Country { get; set; }
#nullable restore
#else
        public string Country { get; set; }
#endif
        /// <summary>Represents a Japan-only address format. This field will only appear on orders placed from Japan.</summary>
        public global::Soenneker.Webflow.OpenApiClient.Models.UnfulfillOrder200ResponseAllAddressesItemJapanType? JapanType { get; set; }
        /// <summary>The first line of the address</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Line1 { get; set; }
#nullable restore
#else
        public string Line1 { get; set; }
#endif
        /// <summary>The second line of the address</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Line2 { get; set; }
#nullable restore
#else
        public string Line2 { get; set; }
#endif
        /// <summary>The postal code of the address</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PostalCode { get; set; }
#nullable restore
#else
        public string PostalCode { get; set; }
#endif
        /// <summary>The state or province of the address</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? State { get; set; }
#nullable restore
#else
        public string State { get; set; }
#endif
        /// <summary>The type of the order address (billing or shipping)</summary>
        public global::Soenneker.Webflow.OpenApiClient.Models.UnfulfillOrder200ResponseAllAddressesItemType? Type { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Webflow.OpenApiClient.Models.UnfulfillOrder200ResponseAllAddressesItem"/> and sets the default values.
        /// </summary>
        public UnfulfillOrder200ResponseAllAddressesItem()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Webflow.OpenApiClient.Models.UnfulfillOrder200ResponseAllAddressesItem"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Webflow.OpenApiClient.Models.UnfulfillOrder200ResponseAllAddressesItem CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Webflow.OpenApiClient.Models.UnfulfillOrder200ResponseAllAddressesItem();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "addressee", n => { Addressee = n.GetStringValue(); } },
                { "city", n => { City = n.GetStringValue(); } },
                { "country", n => { Country = n.GetStringValue(); } },
                { "japanType", n => { JapanType = n.GetEnumValue<global::Soenneker.Webflow.OpenApiClient.Models.UnfulfillOrder200ResponseAllAddressesItemJapanType>(); } },
                { "line1", n => { Line1 = n.GetStringValue(); } },
                { "line2", n => { Line2 = n.GetStringValue(); } },
                { "postalCode", n => { PostalCode = n.GetStringValue(); } },
                { "state", n => { State = n.GetStringValue(); } },
                { "type", n => { Type = n.GetEnumValue<global::Soenneker.Webflow.OpenApiClient.Models.UnfulfillOrder200ResponseAllAddressesItemType>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("addressee", Addressee);
            writer.WriteStringValue("city", City);
            writer.WriteStringValue("country", Country);
            writer.WriteEnumValue<global::Soenneker.Webflow.OpenApiClient.Models.UnfulfillOrder200ResponseAllAddressesItemJapanType>("japanType", JapanType);
            writer.WriteStringValue("line1", Line1);
            writer.WriteStringValue("line2", Line2);
            writer.WriteStringValue("postalCode", PostalCode);
            writer.WriteStringValue("state", State);
            writer.WriteEnumValue<global::Soenneker.Webflow.OpenApiClient.Models.UnfulfillOrder200ResponseAllAddressesItemType>("type", Type);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
