// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Webflow.OpenApiClient.Models
{
    /// <summary>
    /// The updated SKU
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class UpdateSkuRequest : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Indicate whether your Product should be set as &quot;staging&quot; or &quot;live&quot;</summary>
        public global::Soenneker.Webflow.OpenApiClient.Models.UpdateSkuRequestPublishStatus? PublishStatus { get; set; }
        /// <summary>The SKU object</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Webflow.OpenApiClient.Models.UpdateSkuRequestSku? Sku { get; set; }
#nullable restore
#else
        public global::Soenneker.Webflow.OpenApiClient.Models.UpdateSkuRequestSku Sku { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Webflow.OpenApiClient.Models.UpdateSkuRequest"/> and sets the default values.
        /// </summary>
        public UpdateSkuRequest()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Webflow.OpenApiClient.Models.UpdateSkuRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Webflow.OpenApiClient.Models.UpdateSkuRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Webflow.OpenApiClient.Models.UpdateSkuRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "publishStatus", n => { PublishStatus = n.GetEnumValue<global::Soenneker.Webflow.OpenApiClient.Models.UpdateSkuRequestPublishStatus>(); } },
                { "sku", n => { Sku = n.GetObjectValue<global::Soenneker.Webflow.OpenApiClient.Models.UpdateSkuRequestSku>(global::Soenneker.Webflow.OpenApiClient.Models.UpdateSkuRequestSku.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::Soenneker.Webflow.OpenApiClient.Models.UpdateSkuRequestPublishStatus>("publishStatus", PublishStatus);
            writer.WriteObjectValue<global::Soenneker.Webflow.OpenApiClient.Models.UpdateSkuRequestSku>("sku", Sku);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
