// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Webflow.OpenApiClient.Models
{
    /// <summary>
    /// The Product object
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class UpdateProductRequestProduct : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Identifier for the locale of the CMS item</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CmsLocaleId { get; private set; }
#nullable restore
#else
        public string CmsLocaleId { get; private set; }
#endif
        /// <summary>The date the Product was created</summary>
        public DateTimeOffset? CreatedOn { get; private set; }
        /// <summary>Contains content-specific details for a product, covering both standard (e.g., title, description) and custom fields tailored to the product setup.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Webflow.OpenApiClient.Models.UpdateProductRequestProductFieldData? FieldData { get; set; }
#nullable restore
#else
        public global::Soenneker.Webflow.OpenApiClient.Models.UpdateProductRequestProductFieldData FieldData { get; set; }
#endif
        /// <summary>Unique identifier for the Product</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; private set; }
#nullable restore
#else
        public string Id { get; private set; }
#endif
        /// <summary>Boolean determining if the Product is set to archived</summary>
        public bool? IsArchived { get; set; }
        /// <summary>Boolean determining if the Product is set to draft</summary>
        public bool? IsDraft { get; set; }
        /// <summary>The date the Product was last published</summary>
        public DateTimeOffset? LastPublished { get; private set; }
        /// <summary>The date the Product was last updated</summary>
        public DateTimeOffset? LastUpdated { get; private set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Webflow.OpenApiClient.Models.UpdateProductRequestProduct"/> and sets the default values.
        /// </summary>
        public UpdateProductRequestProduct()
        {
            AdditionalData = new Dictionary<string, object>();
            IsArchived = false;
            IsDraft = false;
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Webflow.OpenApiClient.Models.UpdateProductRequestProduct"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Webflow.OpenApiClient.Models.UpdateProductRequestProduct CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Webflow.OpenApiClient.Models.UpdateProductRequestProduct();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "cmsLocaleId", n => { CmsLocaleId = n.GetStringValue(); } },
                { "createdOn", n => { CreatedOn = n.GetDateTimeOffsetValue(); } },
                { "fieldData", n => { FieldData = n.GetObjectValue<global::Soenneker.Webflow.OpenApiClient.Models.UpdateProductRequestProductFieldData>(global::Soenneker.Webflow.OpenApiClient.Models.UpdateProductRequestProductFieldData.CreateFromDiscriminatorValue); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "isArchived", n => { IsArchived = n.GetBoolValue(); } },
                { "isDraft", n => { IsDraft = n.GetBoolValue(); } },
                { "lastPublished", n => { LastPublished = n.GetDateTimeOffsetValue(); } },
                { "lastUpdated", n => { LastUpdated = n.GetDateTimeOffsetValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Webflow.OpenApiClient.Models.UpdateProductRequestProductFieldData>("fieldData", FieldData);
            writer.WriteBoolValue("isArchived", IsArchived);
            writer.WriteBoolValue("isDraft", IsDraft);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
