// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Webflow.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.Webflow.OpenApiClient.Models.UpdateStaticContentRequestNodesItemComponentInstance"/>, <see cref="global::Soenneker.Webflow.OpenApiClient.Models.UpdateStaticContentRequestNodesItemSearchButton"/>, <see cref="global::Soenneker.Webflow.OpenApiClient.Models.UpdateStaticContentRequestNodesItemSelect"/>, <see cref="global::Soenneker.Webflow.OpenApiClient.Models.UpdateStaticContentRequestNodesItemSubmitButton"/>, <see cref="global::Soenneker.Webflow.OpenApiClient.Models.UpdateStaticContentRequestNodesItemTextInput"/>, <see cref="global::Soenneker.Webflow.OpenApiClient.Models.UpdateStaticContentRequestNodesItemTextNode"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class UpdateStaticContentRequestNodesItem : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Webflow.OpenApiClient.Models.UpdateStaticContentRequestNodesItemComponentInstance"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Webflow.OpenApiClient.Models.UpdateStaticContentRequestNodesItemComponentInstance? UpdateStaticContentRequestNodesItemComponentInstance { get; set; }
#nullable restore
#else
        public global::Soenneker.Webflow.OpenApiClient.Models.UpdateStaticContentRequestNodesItemComponentInstance UpdateStaticContentRequestNodesItemComponentInstance { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Webflow.OpenApiClient.Models.UpdateStaticContentRequestNodesItemSearchButton"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Webflow.OpenApiClient.Models.UpdateStaticContentRequestNodesItemSearchButton? UpdateStaticContentRequestNodesItemSearchButton { get; set; }
#nullable restore
#else
        public global::Soenneker.Webflow.OpenApiClient.Models.UpdateStaticContentRequestNodesItemSearchButton UpdateStaticContentRequestNodesItemSearchButton { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Webflow.OpenApiClient.Models.UpdateStaticContentRequestNodesItemSelect"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Webflow.OpenApiClient.Models.UpdateStaticContentRequestNodesItemSelect? UpdateStaticContentRequestNodesItemSelect { get; set; }
#nullable restore
#else
        public global::Soenneker.Webflow.OpenApiClient.Models.UpdateStaticContentRequestNodesItemSelect UpdateStaticContentRequestNodesItemSelect { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Webflow.OpenApiClient.Models.UpdateStaticContentRequestNodesItemSubmitButton"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Webflow.OpenApiClient.Models.UpdateStaticContentRequestNodesItemSubmitButton? UpdateStaticContentRequestNodesItemSubmitButton { get; set; }
#nullable restore
#else
        public global::Soenneker.Webflow.OpenApiClient.Models.UpdateStaticContentRequestNodesItemSubmitButton UpdateStaticContentRequestNodesItemSubmitButton { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Webflow.OpenApiClient.Models.UpdateStaticContentRequestNodesItemTextInput"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Webflow.OpenApiClient.Models.UpdateStaticContentRequestNodesItemTextInput? UpdateStaticContentRequestNodesItemTextInput { get; set; }
#nullable restore
#else
        public global::Soenneker.Webflow.OpenApiClient.Models.UpdateStaticContentRequestNodesItemTextInput UpdateStaticContentRequestNodesItemTextInput { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Webflow.OpenApiClient.Models.UpdateStaticContentRequestNodesItemTextNode"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Webflow.OpenApiClient.Models.UpdateStaticContentRequestNodesItemTextNode? UpdateStaticContentRequestNodesItemTextNode { get; set; }
#nullable restore
#else
        public global::Soenneker.Webflow.OpenApiClient.Models.UpdateStaticContentRequestNodesItemTextNode UpdateStaticContentRequestNodesItemTextNode { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Webflow.OpenApiClient.Models.UpdateStaticContentRequestNodesItem"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Webflow.OpenApiClient.Models.UpdateStaticContentRequestNodesItem CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
            var result = new global::Soenneker.Webflow.OpenApiClient.Models.UpdateStaticContentRequestNodesItem();
            if("UpdateStaticContentRequestNodesItemComponentInstance".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.UpdateStaticContentRequestNodesItemComponentInstance = new global::Soenneker.Webflow.OpenApiClient.Models.UpdateStaticContentRequestNodesItemComponentInstance();
            }
            else if("UpdateStaticContentRequestNodesItemSearchButton".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.UpdateStaticContentRequestNodesItemSearchButton = new global::Soenneker.Webflow.OpenApiClient.Models.UpdateStaticContentRequestNodesItemSearchButton();
            }
            else if("UpdateStaticContentRequestNodesItemSelect".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.UpdateStaticContentRequestNodesItemSelect = new global::Soenneker.Webflow.OpenApiClient.Models.UpdateStaticContentRequestNodesItemSelect();
            }
            else if("UpdateStaticContentRequestNodesItemSubmitButton".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.UpdateStaticContentRequestNodesItemSubmitButton = new global::Soenneker.Webflow.OpenApiClient.Models.UpdateStaticContentRequestNodesItemSubmitButton();
            }
            else if("UpdateStaticContentRequestNodesItemTextInput".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.UpdateStaticContentRequestNodesItemTextInput = new global::Soenneker.Webflow.OpenApiClient.Models.UpdateStaticContentRequestNodesItemTextInput();
            }
            else if("UpdateStaticContentRequestNodesItemTextNode".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.UpdateStaticContentRequestNodesItemTextNode = new global::Soenneker.Webflow.OpenApiClient.Models.UpdateStaticContentRequestNodesItemTextNode();
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(UpdateStaticContentRequestNodesItemComponentInstance != null)
            {
                return UpdateStaticContentRequestNodesItemComponentInstance.GetFieldDeserializers();
            }
            else if(UpdateStaticContentRequestNodesItemSearchButton != null)
            {
                return UpdateStaticContentRequestNodesItemSearchButton.GetFieldDeserializers();
            }
            else if(UpdateStaticContentRequestNodesItemSelect != null)
            {
                return UpdateStaticContentRequestNodesItemSelect.GetFieldDeserializers();
            }
            else if(UpdateStaticContentRequestNodesItemSubmitButton != null)
            {
                return UpdateStaticContentRequestNodesItemSubmitButton.GetFieldDeserializers();
            }
            else if(UpdateStaticContentRequestNodesItemTextInput != null)
            {
                return UpdateStaticContentRequestNodesItemTextInput.GetFieldDeserializers();
            }
            else if(UpdateStaticContentRequestNodesItemTextNode != null)
            {
                return UpdateStaticContentRequestNodesItemTextNode.GetFieldDeserializers();
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(UpdateStaticContentRequestNodesItemComponentInstance != null)
            {
                writer.WriteObjectValue<global::Soenneker.Webflow.OpenApiClient.Models.UpdateStaticContentRequestNodesItemComponentInstance>(null, UpdateStaticContentRequestNodesItemComponentInstance);
            }
            else if(UpdateStaticContentRequestNodesItemSearchButton != null)
            {
                writer.WriteObjectValue<global::Soenneker.Webflow.OpenApiClient.Models.UpdateStaticContentRequestNodesItemSearchButton>(null, UpdateStaticContentRequestNodesItemSearchButton);
            }
            else if(UpdateStaticContentRequestNodesItemSelect != null)
            {
                writer.WriteObjectValue<global::Soenneker.Webflow.OpenApiClient.Models.UpdateStaticContentRequestNodesItemSelect>(null, UpdateStaticContentRequestNodesItemSelect);
            }
            else if(UpdateStaticContentRequestNodesItemSubmitButton != null)
            {
                writer.WriteObjectValue<global::Soenneker.Webflow.OpenApiClient.Models.UpdateStaticContentRequestNodesItemSubmitButton>(null, UpdateStaticContentRequestNodesItemSubmitButton);
            }
            else if(UpdateStaticContentRequestNodesItemTextInput != null)
            {
                writer.WriteObjectValue<global::Soenneker.Webflow.OpenApiClient.Models.UpdateStaticContentRequestNodesItemTextInput>(null, UpdateStaticContentRequestNodesItemTextInput);
            }
            else if(UpdateStaticContentRequestNodesItemTextNode != null)
            {
                writer.WriteObjectValue<global::Soenneker.Webflow.OpenApiClient.Models.UpdateStaticContentRequestNodesItemTextNode>(null, UpdateStaticContentRequestNodesItemTextNode);
            }
        }
    }
}
#pragma warning restore CS0618
