// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Webflow.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.Webflow.OpenApiClient.Models.UpdateField200ApplicationJsonValidationsAdditionalPropertiesBranch1"/>, <see cref="global::Soenneker.Webflow.OpenApiClient.Models.UpdateField200ApplicationJsonValidationsAdditionalPropertiesBranch2"/>, <see cref="global::Soenneker.Webflow.OpenApiClient.Models.UpdateField200ApplicationJsonValidationsAdditionalPropertiesBranch3"/>, <see cref="global::Soenneker.Webflow.OpenApiClient.Models.UpdateField200ApplicationJsonValidationsAdditionalPropertiesBranch4"/>, <see cref="global::Soenneker.Webflow.OpenApiClient.Models.UpdateField200ResponseValidationsAdditionalPropertiesMember1"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class UpdateField200ResponseValidationsAdditionalProperties : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Webflow.OpenApiClient.Models.UpdateField200ApplicationJsonValidationsAdditionalPropertiesBranch1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Webflow.OpenApiClient.Models.UpdateField200ApplicationJsonValidationsAdditionalPropertiesBranch1? UpdateField200ApplicationJsonValidationsAdditionalPropertiesBranch1 { get; set; }
#nullable restore
#else
        public global::Soenneker.Webflow.OpenApiClient.Models.UpdateField200ApplicationJsonValidationsAdditionalPropertiesBranch1 UpdateField200ApplicationJsonValidationsAdditionalPropertiesBranch1 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Webflow.OpenApiClient.Models.UpdateField200ApplicationJsonValidationsAdditionalPropertiesBranch2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Webflow.OpenApiClient.Models.UpdateField200ApplicationJsonValidationsAdditionalPropertiesBranch2? UpdateField200ApplicationJsonValidationsAdditionalPropertiesBranch2 { get; set; }
#nullable restore
#else
        public global::Soenneker.Webflow.OpenApiClient.Models.UpdateField200ApplicationJsonValidationsAdditionalPropertiesBranch2 UpdateField200ApplicationJsonValidationsAdditionalPropertiesBranch2 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Webflow.OpenApiClient.Models.UpdateField200ApplicationJsonValidationsAdditionalPropertiesBranch3"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Webflow.OpenApiClient.Models.UpdateField200ApplicationJsonValidationsAdditionalPropertiesBranch3? UpdateField200ApplicationJsonValidationsAdditionalPropertiesBranch3 { get; set; }
#nullable restore
#else
        public global::Soenneker.Webflow.OpenApiClient.Models.UpdateField200ApplicationJsonValidationsAdditionalPropertiesBranch3 UpdateField200ApplicationJsonValidationsAdditionalPropertiesBranch3 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Webflow.OpenApiClient.Models.UpdateField200ApplicationJsonValidationsAdditionalPropertiesBranch4"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Webflow.OpenApiClient.Models.UpdateField200ApplicationJsonValidationsAdditionalPropertiesBranch4? UpdateField200ApplicationJsonValidationsAdditionalPropertiesBranch4 { get; set; }
#nullable restore
#else
        public global::Soenneker.Webflow.OpenApiClient.Models.UpdateField200ApplicationJsonValidationsAdditionalPropertiesBranch4 UpdateField200ApplicationJsonValidationsAdditionalPropertiesBranch4 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Webflow.OpenApiClient.Models.UpdateField200ResponseValidationsAdditionalPropertiesMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Webflow.OpenApiClient.Models.UpdateField200ResponseValidationsAdditionalPropertiesMember1? UpdateField200ResponseValidationsAdditionalPropertiesMember1 { get; set; }
#nullable restore
#else
        public global::Soenneker.Webflow.OpenApiClient.Models.UpdateField200ResponseValidationsAdditionalPropertiesMember1 UpdateField200ResponseValidationsAdditionalPropertiesMember1 { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Webflow.OpenApiClient.Models.UpdateField200ResponseValidationsAdditionalProperties"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Webflow.OpenApiClient.Models.UpdateField200ResponseValidationsAdditionalProperties CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
            var result = new global::Soenneker.Webflow.OpenApiClient.Models.UpdateField200ResponseValidationsAdditionalProperties();
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(UpdateField200ApplicationJsonValidationsAdditionalPropertiesBranch1 != null)
            {
                return UpdateField200ApplicationJsonValidationsAdditionalPropertiesBranch1.GetFieldDeserializers();
            }
            else if(UpdateField200ApplicationJsonValidationsAdditionalPropertiesBranch2 != null)
            {
                return UpdateField200ApplicationJsonValidationsAdditionalPropertiesBranch2.GetFieldDeserializers();
            }
            else if(UpdateField200ApplicationJsonValidationsAdditionalPropertiesBranch3 != null)
            {
                return UpdateField200ApplicationJsonValidationsAdditionalPropertiesBranch3.GetFieldDeserializers();
            }
            else if(UpdateField200ApplicationJsonValidationsAdditionalPropertiesBranch4 != null)
            {
                return UpdateField200ApplicationJsonValidationsAdditionalPropertiesBranch4.GetFieldDeserializers();
            }
            else if(UpdateField200ResponseValidationsAdditionalPropertiesMember1 != null)
            {
                return UpdateField200ResponseValidationsAdditionalPropertiesMember1.GetFieldDeserializers();
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(UpdateField200ApplicationJsonValidationsAdditionalPropertiesBranch1 != null)
            {
                writer.WriteObjectValue<global::Soenneker.Webflow.OpenApiClient.Models.UpdateField200ApplicationJsonValidationsAdditionalPropertiesBranch1>(null, UpdateField200ApplicationJsonValidationsAdditionalPropertiesBranch1);
            }
            else if(UpdateField200ApplicationJsonValidationsAdditionalPropertiesBranch2 != null)
            {
                writer.WriteObjectValue<global::Soenneker.Webflow.OpenApiClient.Models.UpdateField200ApplicationJsonValidationsAdditionalPropertiesBranch2>(null, UpdateField200ApplicationJsonValidationsAdditionalPropertiesBranch2);
            }
            else if(UpdateField200ApplicationJsonValidationsAdditionalPropertiesBranch3 != null)
            {
                writer.WriteObjectValue<global::Soenneker.Webflow.OpenApiClient.Models.UpdateField200ApplicationJsonValidationsAdditionalPropertiesBranch3>(null, UpdateField200ApplicationJsonValidationsAdditionalPropertiesBranch3);
            }
            else if(UpdateField200ApplicationJsonValidationsAdditionalPropertiesBranch4 != null)
            {
                writer.WriteObjectValue<global::Soenneker.Webflow.OpenApiClient.Models.UpdateField200ApplicationJsonValidationsAdditionalPropertiesBranch4>(null, UpdateField200ApplicationJsonValidationsAdditionalPropertiesBranch4);
            }
            else if(UpdateField200ResponseValidationsAdditionalPropertiesMember1 != null)
            {
                writer.WriteObjectValue<global::Soenneker.Webflow.OpenApiClient.Models.UpdateField200ResponseValidationsAdditionalPropertiesMember1>(null, UpdateField200ResponseValidationsAdditionalPropertiesMember1);
            }
        }
    }
}
#pragma warning restore CS0618
