// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Webflow.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum WorkspaceMembershipEventType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "workspace_membership")]
        #pragma warning disable CS1591
        WorkspaceMembership,
        #pragma warning restore CS1591
    }
}
