// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Webflow.OpenApiClient.Collections.Item.Fields;
using Soenneker.Webflow.OpenApiClient.Collections.Item.Items;
using Soenneker.Webflow.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Webflow.OpenApiClient.Collections.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \collections\{collection-id}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CollectionItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The fields property</summary>
        public global::Soenneker.Webflow.OpenApiClient.Collections.Item.Fields.FieldsRequestBuilder Fields
        {
            get => new global::Soenneker.Webflow.OpenApiClient.Collections.Item.Fields.FieldsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The items property</summary>
        public global::Soenneker.Webflow.OpenApiClient.Collections.Item.Items.ItemsRequestBuilder Items
        {
            get => new global::Soenneker.Webflow.OpenApiClient.Collections.Item.Items.ItemsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Webflow.OpenApiClient.Collections.Item.CollectionItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CollectionItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/collections/{collection%2Did}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Webflow.OpenApiClient.Collections.Item.CollectionItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CollectionItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/collections/{collection%2Did}", rawUrl)
        {
        }
        /// <summary>
        /// Delete a collection using its ID.Required scope | `cms:write`
        /// </summary>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Webflow.OpenApiClient.Models.DeleteCollection400Response">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Webflow.OpenApiClient.Models.DeleteCollection401Response">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Webflow.OpenApiClient.Models.DeleteCollection404Response">When receiving a 404 status code</exception>
        /// <exception cref="global::Soenneker.Webflow.OpenApiClient.Models.DeleteCollection429Response">When receiving a 429 status code</exception>
        /// <exception cref="global::Soenneker.Webflow.OpenApiClient.Models.DeleteCollection500Response">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task DeleteAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task DeleteAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToDeleteRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Webflow.OpenApiClient.Models.DeleteCollection400Response.CreateFromDiscriminatorValue },
                { "401", global::Soenneker.Webflow.OpenApiClient.Models.DeleteCollection401Response.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.Webflow.OpenApiClient.Models.DeleteCollection404Response.CreateFromDiscriminatorValue },
                { "429", global::Soenneker.Webflow.OpenApiClient.Models.DeleteCollection429Response.CreateFromDiscriminatorValue },
                { "500", global::Soenneker.Webflow.OpenApiClient.Models.DeleteCollection500Response.CreateFromDiscriminatorValue },
            };
            await RequestAdapter.SendNoContentAsync(requestInfo, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Get the full details of a collection from its ID.Required scope | `cms:read`
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Webflow.OpenApiClient.Models.CollectionDetails200Response"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Webflow.OpenApiClient.Models.CollectionDetails400Response">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Webflow.OpenApiClient.Models.CollectionDetails401Response">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Webflow.OpenApiClient.Models.CollectionDetails404Response">When receiving a 404 status code</exception>
        /// <exception cref="global::Soenneker.Webflow.OpenApiClient.Models.CollectionDetails429Response">When receiving a 429 status code</exception>
        /// <exception cref="global::Soenneker.Webflow.OpenApiClient.Models.CollectionDetails500Response">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Webflow.OpenApiClient.Models.CollectionDetails200Response?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Webflow.OpenApiClient.Models.CollectionDetails200Response> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Webflow.OpenApiClient.Models.CollectionDetails400Response.CreateFromDiscriminatorValue },
                { "401", global::Soenneker.Webflow.OpenApiClient.Models.CollectionDetails401Response.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.Webflow.OpenApiClient.Models.CollectionDetails404Response.CreateFromDiscriminatorValue },
                { "429", global::Soenneker.Webflow.OpenApiClient.Models.CollectionDetails429Response.CreateFromDiscriminatorValue },
                { "500", global::Soenneker.Webflow.OpenApiClient.Models.CollectionDetails500Response.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Webflow.OpenApiClient.Models.CollectionDetails200Response>(requestInfo, global::Soenneker.Webflow.OpenApiClient.Models.CollectionDetails200Response.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Update a collection&apos;s display name, singular name, slug, or field groups.**Field group rules:**- A collection can have a maximum of 50 field groups- Each `displayName` must be unique across all field groups in the collection- Each `fieldId` must be unique across all field groups in the collection- Ecommerce collections do not support field groupsRequired scope | `cms:write`
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Webflow.OpenApiClient.Models.PatchCollection200Response"/></returns>
        /// <param name="body">The properties to update on a collection</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Webflow.OpenApiClient.Models.PatchCollection400Response">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Webflow.OpenApiClient.Models.PatchCollection401Response">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Webflow.OpenApiClient.Models.PatchCollection404Response">When receiving a 404 status code</exception>
        /// <exception cref="global::Soenneker.Webflow.OpenApiClient.Models.PatchCollection429Response">When receiving a 429 status code</exception>
        /// <exception cref="global::Soenneker.Webflow.OpenApiClient.Models.PatchCollection500Response">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Webflow.OpenApiClient.Models.PatchCollection200Response?> PatchAsync(global::Soenneker.Webflow.OpenApiClient.Models.PatchCollectionRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Webflow.OpenApiClient.Models.PatchCollection200Response> PatchAsync(global::Soenneker.Webflow.OpenApiClient.Models.PatchCollectionRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPatchRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Webflow.OpenApiClient.Models.PatchCollection400Response.CreateFromDiscriminatorValue },
                { "401", global::Soenneker.Webflow.OpenApiClient.Models.PatchCollection401Response.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.Webflow.OpenApiClient.Models.PatchCollection404Response.CreateFromDiscriminatorValue },
                { "429", global::Soenneker.Webflow.OpenApiClient.Models.PatchCollection429Response.CreateFromDiscriminatorValue },
                { "500", global::Soenneker.Webflow.OpenApiClient.Models.PatchCollection500Response.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Webflow.OpenApiClient.Models.PatchCollection200Response>(requestInfo, global::Soenneker.Webflow.OpenApiClient.Models.PatchCollection200Response.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Delete a collection using its ID.Required scope | `cms:write`
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.DELETE, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Get the full details of a collection from its ID.Required scope | `cms:read`
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Update a collection&apos;s display name, singular name, slug, or field groups.**Field group rules:**- A collection can have a maximum of 50 field groups- Each `displayName` must be unique across all field groups in the collection- Each `fieldId` must be unique across all field groups in the collection- Ecommerce collections do not support field groupsRequired scope | `cms:write`
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The properties to update on a collection</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPatchRequestInformation(global::Soenneker.Webflow.OpenApiClient.Models.PatchCollectionRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPatchRequestInformation(global::Soenneker.Webflow.OpenApiClient.Models.PatchCollectionRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.PATCH, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Webflow.OpenApiClient.Collections.Item.CollectionItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Webflow.OpenApiClient.Collections.Item.CollectionItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Webflow.OpenApiClient.Collections.Item.CollectionItemRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#pragma warning restore CS0618
