// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Webflow.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Webflow.OpenApiClient.Sites.Item.Orders.Item.Unfulfill
{
    /// <summary>
    /// Builds and executes requests for operations under \sites\{siteId}\orders\{orderId}\unfulfill
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class UnfulfillRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Webflow.OpenApiClient.Sites.Item.Orders.Item.Unfulfill.UnfulfillRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public UnfulfillRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/sites/{siteId}/orders/{orderId}/unfulfill", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Webflow.OpenApiClient.Sites.Item.Orders.Item.Unfulfill.UnfulfillRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public UnfulfillRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/sites/{siteId}/orders/{orderId}/unfulfill", rawUrl)
        {
        }
        /// <summary>
        /// Updates an order&apos;s status to unfulfilledRequired scope | `ecommerce:write`
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Webflow.OpenApiClient.Models.UnfulfillOrder200Response"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Webflow.OpenApiClient.Models.UnfulfillOrder400Response">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Webflow.OpenApiClient.Models.UnfulfillOrder401Response">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Webflow.OpenApiClient.Models.UnfulfillOrder403Response">When receiving a 403 status code</exception>
        /// <exception cref="global::Soenneker.Webflow.OpenApiClient.Models.UnfulfillOrder404Response">When receiving a 404 status code</exception>
        /// <exception cref="global::Soenneker.Webflow.OpenApiClient.Models.UnfulfillOrder409Response">When receiving a 409 status code</exception>
        /// <exception cref="global::Soenneker.Webflow.OpenApiClient.Models.UnfulfillOrder429Response">When receiving a 429 status code</exception>
        /// <exception cref="global::Soenneker.Webflow.OpenApiClient.Models.UnfulfillOrder500Response">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Webflow.OpenApiClient.Models.UnfulfillOrder200Response?> PostAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Webflow.OpenApiClient.Models.UnfulfillOrder200Response> PostAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToPostRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Webflow.OpenApiClient.Models.UnfulfillOrder400Response.CreateFromDiscriminatorValue },
                { "401", global::Soenneker.Webflow.OpenApiClient.Models.UnfulfillOrder401Response.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.Webflow.OpenApiClient.Models.UnfulfillOrder403Response.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.Webflow.OpenApiClient.Models.UnfulfillOrder404Response.CreateFromDiscriminatorValue },
                { "409", global::Soenneker.Webflow.OpenApiClient.Models.UnfulfillOrder409Response.CreateFromDiscriminatorValue },
                { "429", global::Soenneker.Webflow.OpenApiClient.Models.UnfulfillOrder429Response.CreateFromDiscriminatorValue },
                { "500", global::Soenneker.Webflow.OpenApiClient.Models.UnfulfillOrder500Response.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Webflow.OpenApiClient.Models.UnfulfillOrder200Response>(requestInfo, global::Soenneker.Webflow.OpenApiClient.Models.UnfulfillOrder200Response.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Updates an order&apos;s status to unfulfilledRequired scope | `ecommerce:write`
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Webflow.OpenApiClient.Sites.Item.Orders.Item.Unfulfill.UnfulfillRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Webflow.OpenApiClient.Sites.Item.Orders.Item.Unfulfill.UnfulfillRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Webflow.OpenApiClient.Sites.Item.Orders.Item.Unfulfill.UnfulfillRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#pragma warning restore CS0618
